// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: version/version.proto

package versionpb

import (
	common "github.com/anychat/server/api/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckVersionRequest 版本检测请求
type CheckVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`                           // 平台: ios/android/pc/web/h5
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                             // 当前版本号，如 1.0.0
	BuildNumber   int32                  `protobuf:"varint,3,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"` // 构建号（iOS/Android）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckVersionRequest) Reset() {
	*x = CheckVersionRequest{}
	mi := &file_version_version_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckVersionRequest) ProtoMessage() {}

func (x *CheckVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckVersionRequest.ProtoReflect.Descriptor instead.
func (*CheckVersionRequest) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{0}
}

func (x *CheckVersionRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CheckVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CheckVersionRequest) GetBuildNumber() int32 {
	if x != nil {
		return x.BuildNumber
	}
	return 0
}

// CheckVersionResponse 版本检测响应
type CheckVersionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HasUpdate         bool                   `protobuf:"varint,1,opt,name=has_update,json=hasUpdate,proto3" json:"has_update,omitempty"`
	LatestVersion     string                 `protobuf:"bytes,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	LatestBuildNumber int32                  `protobuf:"varint,3,opt,name=latest_build_number,json=latestBuildNumber,proto3" json:"latest_build_number,omitempty"`
	ForceUpdate       bool                   `protobuf:"varint,4,opt,name=force_update,json=forceUpdate,proto3" json:"force_update,omitempty"`
	MinVersion        string                 `protobuf:"bytes,5,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	MinBuildNumber    int32                  `protobuf:"varint,6,opt,name=min_build_number,json=minBuildNumber,proto3" json:"min_build_number,omitempty"`
	UpdateInfo        *UpdateInfo            `protobuf:"bytes,7,opt,name=update_info,json=updateInfo,proto3" json:"update_info,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckVersionResponse) Reset() {
	*x = CheckVersionResponse{}
	mi := &file_version_version_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckVersionResponse) ProtoMessage() {}

func (x *CheckVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckVersionResponse.ProtoReflect.Descriptor instead.
func (*CheckVersionResponse) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{1}
}

func (x *CheckVersionResponse) GetHasUpdate() bool {
	if x != nil {
		return x.HasUpdate
	}
	return false
}

func (x *CheckVersionResponse) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *CheckVersionResponse) GetLatestBuildNumber() int32 {
	if x != nil {
		return x.LatestBuildNumber
	}
	return 0
}

func (x *CheckVersionResponse) GetForceUpdate() bool {
	if x != nil {
		return x.ForceUpdate
	}
	return false
}

func (x *CheckVersionResponse) GetMinVersion() string {
	if x != nil {
		return x.MinVersion
	}
	return ""
}

func (x *CheckVersionResponse) GetMinBuildNumber() int32 {
	if x != nil {
		return x.MinBuildNumber
	}
	return 0
}

func (x *CheckVersionResponse) GetUpdateInfo() *UpdateInfo {
	if x != nil {
		return x.UpdateInfo
	}
	return nil
}

// UpdateInfo 更新信息
type UpdateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,3,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileHash      string                 `protobuf:"bytes,5,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInfo) Reset() {
	*x = UpdateInfo{}
	mi := &file_version_version_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInfo) ProtoMessage() {}

func (x *UpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInfo.ProtoReflect.Descriptor instead.
func (*UpdateInfo) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateInfo) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *UpdateInfo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UpdateInfo) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

// GetLatestVersionRequest 获取最新版本请求
type GetLatestVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	ReleaseType   string                 `protobuf:"bytes,2,opt,name=release_type,json=releaseType,proto3" json:"release_type,omitempty"` // stable/beta/alpha
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestVersionRequest) Reset() {
	*x = GetLatestVersionRequest{}
	mi := &file_version_version_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestVersionRequest) ProtoMessage() {}

func (x *GetLatestVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestVersionRequest.ProtoReflect.Descriptor instead.
func (*GetLatestVersionRequest) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{3}
}

func (x *GetLatestVersionRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetLatestVersionRequest) GetReleaseType() string {
	if x != nil {
		return x.ReleaseType
	}
	return ""
}

// GetLatestVersionResponse 获取最新版本响应
type GetLatestVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *VersionInfo           `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestVersionResponse) Reset() {
	*x = GetLatestVersionResponse{}
	mi := &file_version_version_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestVersionResponse) ProtoMessage() {}

func (x *GetLatestVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestVersionResponse.ProtoReflect.Descriptor instead.
func (*GetLatestVersionResponse) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestVersionResponse) GetVersion() *VersionInfo {
	if x != nil {
		return x.Version
	}
	return nil
}

// VersionInfo 版本信息
type VersionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform       string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	BuildNumber    int32                  `protobuf:"varint,4,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	VersionCode    int32                  `protobuf:"varint,5,opt,name=version_code,json=versionCode,proto3" json:"version_code,omitempty"`
	MinVersion     string                 `protobuf:"bytes,6,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	MinBuildNumber int32                  `protobuf:"varint,7,opt,name=min_build_number,json=minBuildNumber,proto3" json:"min_build_number,omitempty"`
	ForceUpdate    bool                   `protobuf:"varint,8,opt,name=force_update,json=forceUpdate,proto3" json:"force_update,omitempty"`
	ReleaseType    string                 `protobuf:"bytes,9,opt,name=release_type,json=releaseType,proto3" json:"release_type,omitempty"`
	Title          string                 `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	Content        string                 `protobuf:"bytes,11,opt,name=content,proto3" json:"content,omitempty"`
	DownloadUrl    string                 `protobuf:"bytes,12,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	FileSize       int64                  `protobuf:"varint,13,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileHash       string                 `protobuf:"bytes,14,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	PublishedAt    string                 `protobuf:"bytes,15,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VersionInfo) Reset() {
	*x = VersionInfo{}
	mi := &file_version_version_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionInfo) ProtoMessage() {}

func (x *VersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionInfo.ProtoReflect.Descriptor instead.
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{5}
}

func (x *VersionInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VersionInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *VersionInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionInfo) GetBuildNumber() int32 {
	if x != nil {
		return x.BuildNumber
	}
	return 0
}

func (x *VersionInfo) GetVersionCode() int32 {
	if x != nil {
		return x.VersionCode
	}
	return 0
}

func (x *VersionInfo) GetMinVersion() string {
	if x != nil {
		return x.MinVersion
	}
	return ""
}

func (x *VersionInfo) GetMinBuildNumber() int32 {
	if x != nil {
		return x.MinBuildNumber
	}
	return 0
}

func (x *VersionInfo) GetForceUpdate() bool {
	if x != nil {
		return x.ForceUpdate
	}
	return false
}

func (x *VersionInfo) GetReleaseType() string {
	if x != nil {
		return x.ReleaseType
	}
	return ""
}

func (x *VersionInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VersionInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *VersionInfo) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *VersionInfo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *VersionInfo) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *VersionInfo) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

// ListVersionsRequest 获取版本列表请求
type ListVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	ReleaseType   string                 `protobuf:"bytes,2,opt,name=release_type,json=releaseType,proto3" json:"release_type,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_version_version_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{6}
}

func (x *ListVersionsRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ListVersionsRequest) GetReleaseType() string {
	if x != nil {
		return x.ReleaseType
	}
	return ""
}

func (x *ListVersionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVersionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListVersionsResponse 获取版本列表响应
type ListVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Versions      []*VersionInfo         `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	mi := &file_version_version_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{7}
}

func (x *ListVersionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListVersionsResponse) GetVersions() []*VersionInfo {
	if x != nil {
		return x.Versions
	}
	return nil
}

// CreateVersionRequest 创建版本请求
type CreateVersionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Platform       string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	BuildNumber    int32                  `protobuf:"varint,3,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	VersionCode    int32                  `protobuf:"varint,4,opt,name=version_code,json=versionCode,proto3" json:"version_code,omitempty"`
	MinVersion     string                 `protobuf:"bytes,5,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	MinBuildNumber int32                  `protobuf:"varint,6,opt,name=min_build_number,json=minBuildNumber,proto3" json:"min_build_number,omitempty"`
	ForceUpdate    bool                   `protobuf:"varint,7,opt,name=force_update,json=forceUpdate,proto3" json:"force_update,omitempty"`
	ReleaseType    string                 `protobuf:"bytes,8,opt,name=release_type,json=releaseType,proto3" json:"release_type,omitempty"`
	Title          string                 `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	Content        string                 `protobuf:"bytes,10,opt,name=content,proto3" json:"content,omitempty"`
	DownloadUrl    string                 `protobuf:"bytes,11,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	FileSize       int64                  `protobuf:"varint,12,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileHash       string                 `protobuf:"bytes,13,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateVersionRequest) Reset() {
	*x = CreateVersionRequest{}
	mi := &file_version_version_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionRequest) ProtoMessage() {}

func (x *CreateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionRequest.ProtoReflect.Descriptor instead.
func (*CreateVersionRequest) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{8}
}

func (x *CreateVersionRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateVersionRequest) GetBuildNumber() int32 {
	if x != nil {
		return x.BuildNumber
	}
	return 0
}

func (x *CreateVersionRequest) GetVersionCode() int32 {
	if x != nil {
		return x.VersionCode
	}
	return 0
}

func (x *CreateVersionRequest) GetMinVersion() string {
	if x != nil {
		return x.MinVersion
	}
	return ""
}

func (x *CreateVersionRequest) GetMinBuildNumber() int32 {
	if x != nil {
		return x.MinBuildNumber
	}
	return 0
}

func (x *CreateVersionRequest) GetForceUpdate() bool {
	if x != nil {
		return x.ForceUpdate
	}
	return false
}

func (x *CreateVersionRequest) GetReleaseType() string {
	if x != nil {
		return x.ReleaseType
	}
	return ""
}

func (x *CreateVersionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateVersionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateVersionRequest) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *CreateVersionRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *CreateVersionRequest) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

// CreateVersionResponse 创建版本响应
type CreateVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVersionResponse) Reset() {
	*x = CreateVersionResponse{}
	mi := &file_version_version_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionResponse) ProtoMessage() {}

func (x *CreateVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionResponse.ProtoReflect.Descriptor instead.
func (*CreateVersionResponse) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{9}
}

func (x *CreateVersionResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateVersionResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// GetVersionRequest 获取版本详情请求
type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_version_version_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{10}
}

func (x *GetVersionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetVersionResponse 获取版本详情响应
type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *VersionInfo           `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_version_version_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{11}
}

func (x *GetVersionResponse) GetVersion() *VersionInfo {
	if x != nil {
		return x.Version
	}
	return nil
}

// DeleteVersionRequest 删除版本请求
type DeleteVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVersionRequest) Reset() {
	*x = DeleteVersionRequest{}
	mi := &file_version_version_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVersionRequest) ProtoMessage() {}

func (x *DeleteVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVersionRequest.ProtoReflect.Descriptor instead.
func (*DeleteVersionRequest) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteVersionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ReportVersionRequest 上报版本请求
type ReportVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	BuildNumber   int32                  `protobuf:"varint,3,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	OsVersion     string                 `protobuf:"bytes,5,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	SdkVersion    string                 `protobuf:"bytes,6,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportVersionRequest) Reset() {
	*x = ReportVersionRequest{}
	mi := &file_version_version_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportVersionRequest) ProtoMessage() {}

func (x *ReportVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_version_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportVersionRequest.ProtoReflect.Descriptor instead.
func (*ReportVersionRequest) Descriptor() ([]byte, []int) {
	return file_version_version_proto_rawDescGZIP(), []int{13}
}

func (x *ReportVersionRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ReportVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ReportVersionRequest) GetBuildNumber() int32 {
	if x != nil {
		return x.BuildNumber
	}
	return 0
}

func (x *ReportVersionRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ReportVersionRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *ReportVersionRequest) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

var File_version_version_proto protoreflect.FileDescriptor

const file_version_version_proto_rawDesc = "" +
	"\n" +
	"\x15version/version.proto\x12\x0fanychat.version\x1a\x13common/common.proto\"n\n" +
	"\x13CheckVersionRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fbuild_number\x18\x03 \x01(\x05R\vbuildNumber\"\xb8\x02\n" +
	"\x14CheckVersionResponse\x12\x1d\n" +
	"\n" +
	"has_update\x18\x01 \x01(\bR\thasUpdate\x12%\n" +
	"\x0elatest_version\x18\x02 \x01(\tR\rlatestVersion\x12.\n" +
	"\x13latest_build_number\x18\x03 \x01(\x05R\x11latestBuildNumber\x12!\n" +
	"\fforce_update\x18\x04 \x01(\bR\vforceUpdate\x12\x1f\n" +
	"\vmin_version\x18\x05 \x01(\tR\n" +
	"minVersion\x12(\n" +
	"\x10min_build_number\x18\x06 \x01(\x05R\x0eminBuildNumber\x12<\n" +
	"\vupdate_info\x18\a \x01(\v2\x1b.anychat.version.UpdateInfoR\n" +
	"updateInfo\"\x99\x01\n" +
	"\n" +
	"UpdateInfo\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12!\n" +
	"\fdownload_url\x18\x03 \x01(\tR\vdownloadUrl\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tfile_hash\x18\x05 \x01(\tR\bfileHash\"X\n" +
	"\x17GetLatestVersionRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12!\n" +
	"\frelease_type\x18\x02 \x01(\tR\vreleaseType\"R\n" +
	"\x18GetLatestVersionResponse\x126\n" +
	"\aversion\x18\x01 \x01(\v2\x1c.anychat.version.VersionInfoR\aversion\"\xda\x03\n" +
	"\vVersionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12!\n" +
	"\fbuild_number\x18\x04 \x01(\x05R\vbuildNumber\x12!\n" +
	"\fversion_code\x18\x05 \x01(\x05R\vversionCode\x12\x1f\n" +
	"\vmin_version\x18\x06 \x01(\tR\n" +
	"minVersion\x12(\n" +
	"\x10min_build_number\x18\a \x01(\x05R\x0eminBuildNumber\x12!\n" +
	"\fforce_update\x18\b \x01(\bR\vforceUpdate\x12!\n" +
	"\frelease_type\x18\t \x01(\tR\vreleaseType\x12\x14\n" +
	"\x05title\x18\n" +
	" \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\v \x01(\tR\acontent\x12!\n" +
	"\fdownload_url\x18\f \x01(\tR\vdownloadUrl\x12\x1b\n" +
	"\tfile_size\x18\r \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tfile_hash\x18\x0e \x01(\tR\bfileHash\x12!\n" +
	"\fpublished_at\x18\x0f \x01(\tR\vpublishedAt\"\x85\x01\n" +
	"\x13ListVersionsRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12!\n" +
	"\frelease_type\x18\x02 \x01(\tR\vreleaseType\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"f\n" +
	"\x14ListVersionsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x128\n" +
	"\bversions\x18\x02 \x03(\v2\x1c.anychat.version.VersionInfoR\bversions\"\xb0\x03\n" +
	"\x14CreateVersionRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fbuild_number\x18\x03 \x01(\x05R\vbuildNumber\x12!\n" +
	"\fversion_code\x18\x04 \x01(\x05R\vversionCode\x12\x1f\n" +
	"\vmin_version\x18\x05 \x01(\tR\n" +
	"minVersion\x12(\n" +
	"\x10min_build_number\x18\x06 \x01(\x05R\x0eminBuildNumber\x12!\n" +
	"\fforce_update\x18\a \x01(\bR\vforceUpdate\x12!\n" +
	"\frelease_type\x18\b \x01(\tR\vreleaseType\x12\x14\n" +
	"\x05title\x18\t \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\n" +
	" \x01(\tR\acontent\x12!\n" +
	"\fdownload_url\x18\v \x01(\tR\vdownloadUrl\x12\x1b\n" +
	"\tfile_size\x18\f \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tfile_hash\x18\r \x01(\tR\bfileHash\"]\n" +
	"\x15CreateVersionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"#\n" +
	"\x11GetVersionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"L\n" +
	"\x12GetVersionResponse\x126\n" +
	"\aversion\x18\x01 \x01(\v2\x1c.anychat.version.VersionInfoR\aversion\"&\n" +
	"\x14DeleteVersionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xcc\x01\n" +
	"\x14ReportVersionRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fbuild_number\x18\x03 \x01(\x05R\vbuildNumber\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"os_version\x18\x05 \x01(\tR\tosVersion\x12\x1f\n" +
	"\vsdk_version\x18\x06 \x01(\tR\n" +
	"sdkVersion2\x88\x05\n" +
	"\x0eVersionService\x12[\n" +
	"\fCheckVersion\x12$.anychat.version.CheckVersionRequest\x1a%.anychat.version.CheckVersionResponse\x12g\n" +
	"\x10GetLatestVersion\x12(.anychat.version.GetLatestVersionRequest\x1a).anychat.version.GetLatestVersionResponse\x12[\n" +
	"\fListVersions\x12$.anychat.version.ListVersionsRequest\x1a%.anychat.version.ListVersionsResponse\x12^\n" +
	"\rCreateVersion\x12%.anychat.version.CreateVersionRequest\x1a&.anychat.version.CreateVersionResponse\x12U\n" +
	"\n" +
	"GetVersion\x12\".anychat.version.GetVersionRequest\x1a#.anychat.version.GetVersionResponse\x12M\n" +
	"\rDeleteVersion\x12%.anychat.version.DeleteVersionRequest\x1a\x15.anychat.common.Empty\x12M\n" +
	"\rReportVersion\x12%.anychat.version.ReportVersionRequest\x1a\x15.anychat.common.EmptyB7Z5github.com/anychat/server/api/proto/version;versionpbb\x06proto3"

var (
	file_version_version_proto_rawDescOnce sync.Once
	file_version_version_proto_rawDescData []byte
)

func file_version_version_proto_rawDescGZIP() []byte {
	file_version_version_proto_rawDescOnce.Do(func() {
		file_version_version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_version_version_proto_rawDesc), len(file_version_version_proto_rawDesc)))
	})
	return file_version_version_proto_rawDescData
}

var file_version_version_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_version_version_proto_goTypes = []any{
	(*CheckVersionRequest)(nil),      // 0: anychat.version.CheckVersionRequest
	(*CheckVersionResponse)(nil),     // 1: anychat.version.CheckVersionResponse
	(*UpdateInfo)(nil),               // 2: anychat.version.UpdateInfo
	(*GetLatestVersionRequest)(nil),  // 3: anychat.version.GetLatestVersionRequest
	(*GetLatestVersionResponse)(nil), // 4: anychat.version.GetLatestVersionResponse
	(*VersionInfo)(nil),              // 5: anychat.version.VersionInfo
	(*ListVersionsRequest)(nil),      // 6: anychat.version.ListVersionsRequest
	(*ListVersionsResponse)(nil),     // 7: anychat.version.ListVersionsResponse
	(*CreateVersionRequest)(nil),     // 8: anychat.version.CreateVersionRequest
	(*CreateVersionResponse)(nil),    // 9: anychat.version.CreateVersionResponse
	(*GetVersionRequest)(nil),        // 10: anychat.version.GetVersionRequest
	(*GetVersionResponse)(nil),       // 11: anychat.version.GetVersionResponse
	(*DeleteVersionRequest)(nil),     // 12: anychat.version.DeleteVersionRequest
	(*ReportVersionRequest)(nil),     // 13: anychat.version.ReportVersionRequest
	(*common.Empty)(nil),             // 14: anychat.common.Empty
}
var file_version_version_proto_depIdxs = []int32{
	2,  // 0: anychat.version.CheckVersionResponse.update_info:type_name -> anychat.version.UpdateInfo
	5,  // 1: anychat.version.GetLatestVersionResponse.version:type_name -> anychat.version.VersionInfo
	5,  // 2: anychat.version.ListVersionsResponse.versions:type_name -> anychat.version.VersionInfo
	5,  // 3: anychat.version.GetVersionResponse.version:type_name -> anychat.version.VersionInfo
	0,  // 4: anychat.version.VersionService.CheckVersion:input_type -> anychat.version.CheckVersionRequest
	3,  // 5: anychat.version.VersionService.GetLatestVersion:input_type -> anychat.version.GetLatestVersionRequest
	6,  // 6: anychat.version.VersionService.ListVersions:input_type -> anychat.version.ListVersionsRequest
	8,  // 7: anychat.version.VersionService.CreateVersion:input_type -> anychat.version.CreateVersionRequest
	10, // 8: anychat.version.VersionService.GetVersion:input_type -> anychat.version.GetVersionRequest
	12, // 9: anychat.version.VersionService.DeleteVersion:input_type -> anychat.version.DeleteVersionRequest
	13, // 10: anychat.version.VersionService.ReportVersion:input_type -> anychat.version.ReportVersionRequest
	1,  // 11: anychat.version.VersionService.CheckVersion:output_type -> anychat.version.CheckVersionResponse
	4,  // 12: anychat.version.VersionService.GetLatestVersion:output_type -> anychat.version.GetLatestVersionResponse
	7,  // 13: anychat.version.VersionService.ListVersions:output_type -> anychat.version.ListVersionsResponse
	9,  // 14: anychat.version.VersionService.CreateVersion:output_type -> anychat.version.CreateVersionResponse
	11, // 15: anychat.version.VersionService.GetVersion:output_type -> anychat.version.GetVersionResponse
	14, // 16: anychat.version.VersionService.DeleteVersion:output_type -> anychat.common.Empty
	14, // 17: anychat.version.VersionService.ReportVersion:output_type -> anychat.common.Empty
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_version_version_proto_init() }
func file_version_version_proto_init() {
	if File_version_version_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_version_version_proto_rawDesc), len(file_version_version_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_version_version_proto_goTypes,
		DependencyIndexes: file_version_version_proto_depIdxs,
		MessageInfos:      file_version_version_proto_msgTypes,
	}.Build()
	File_version_version_proto = out.File
	file_version_version_proto_goTypes = nil
	file_version_version_proto_depIdxs = nil
}
