run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - test
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\_test\\.go$"

linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - goconst
    - gocyclo
    - misspell

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
