// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: sync/sync.proto

package syncpb

import (
	friend "github.com/anychat/server/api/proto/friend"
	group "github.com/anychat/server/api/proto/group"
	message "github.com/anychat/server/api/proto/message"
	session "github.com/anychat/server/api/proto/session"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConversationSeq 会话的最新已知序列号
type ConversationSeq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConversationId   string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ConversationType string                 `protobuf:"bytes,2,opt,name=conversation_type,json=conversationType,proto3" json:"conversation_type,omitempty"` // single/group
	LastSeq          int64                  `protobuf:"varint,3,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConversationSeq) Reset() {
	*x = ConversationSeq{}
	mi := &file_sync_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationSeq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationSeq) ProtoMessage() {}

func (x *ConversationSeq) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationSeq.ProtoReflect.Descriptor instead.
func (*ConversationSeq) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{0}
}

func (x *ConversationSeq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationSeq) GetConversationType() string {
	if x != nil {
		return x.ConversationType
	}
	return ""
}

func (x *ConversationSeq) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

// SyncRequest 同步请求
type SyncRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 上次同步时间（Unix 秒），0 表示全量同步
	LastSyncTime int64 `protobuf:"varint,2,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	// 需要补齐消息的会话列表（只同步有新消息的会话）
	ConversationSeqs []*ConversationSeq `protobuf:"bytes,3,rep,name=conversation_seqs,json=conversationSeqs,proto3" json:"conversation_seqs,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_sync_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SyncRequest) GetLastSyncTime() int64 {
	if x != nil {
		return x.LastSyncTime
	}
	return 0
}

func (x *SyncRequest) GetConversationSeqs() []*ConversationSeq {
	if x != nil {
		return x.ConversationSeqs
	}
	return nil
}

// SyncFriendData 好友增量数据
type SyncFriendData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*friend.Friend       `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFriendData) Reset() {
	*x = SyncFriendData{}
	mi := &file_sync_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFriendData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFriendData) ProtoMessage() {}

func (x *SyncFriendData) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFriendData.ProtoReflect.Descriptor instead.
func (*SyncFriendData) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{2}
}

func (x *SyncFriendData) GetFriends() []*friend.Friend {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *SyncFriendData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// SyncGroupData 群组增量数据
type SyncGroupData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*group.GroupInfo     `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncGroupData) Reset() {
	*x = SyncGroupData{}
	mi := &file_sync_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncGroupData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncGroupData) ProtoMessage() {}

func (x *SyncGroupData) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncGroupData.ProtoReflect.Descriptor instead.
func (*SyncGroupData) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{3}
}

func (x *SyncGroupData) GetGroups() []*group.GroupInfo {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *SyncGroupData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// SyncSessionData 会话增量数据
type SyncSessionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*session.Session     `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSessionData) Reset() {
	*x = SyncSessionData{}
	mi := &file_sync_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSessionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSessionData) ProtoMessage() {}

func (x *SyncSessionData) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSessionData.ProtoReflect.Descriptor instead.
func (*SyncSessionData) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{4}
}

func (x *SyncSessionData) GetSessions() []*session.Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *SyncSessionData) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// ConversationMessages 单个会话的新消息
type ConversationMessages struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConversationId   string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ConversationType string                 `protobuf:"bytes,2,opt,name=conversation_type,json=conversationType,proto3" json:"conversation_type,omitempty"`
	Messages         []*message.Message     `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore          bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConversationMessages) Reset() {
	*x = ConversationMessages{}
	mi := &file_sync_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMessages) ProtoMessage() {}

func (x *ConversationMessages) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMessages.ProtoReflect.Descriptor instead.
func (*ConversationMessages) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{5}
}

func (x *ConversationMessages) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationMessages) GetConversationType() string {
	if x != nil {
		return x.ConversationType
	}
	return ""
}

func (x *ConversationMessages) GetMessages() []*message.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ConversationMessages) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// SyncResponse 同步响应
type SyncResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Friends       *SyncFriendData         `protobuf:"bytes,1,opt,name=friends,proto3" json:"friends,omitempty"`
	Groups        *SyncGroupData          `protobuf:"bytes,2,opt,name=groups,proto3" json:"groups,omitempty"`
	Sessions      *SyncSessionData        `protobuf:"bytes,3,opt,name=sessions,proto3" json:"sessions,omitempty"`
	Conversations []*ConversationMessages `protobuf:"bytes,4,rep,name=conversations,proto3" json:"conversations,omitempty"`
	// 本次同步的服务器时间戳，客户端保存作为下次同步的 last_sync_time
	SyncTime      int64 `protobuf:"varint,5,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_sync_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{6}
}

func (x *SyncResponse) GetFriends() *SyncFriendData {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *SyncResponse) GetGroups() *SyncGroupData {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *SyncResponse) GetSessions() *SyncSessionData {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *SyncResponse) GetConversations() []*ConversationMessages {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *SyncResponse) GetSyncTime() int64 {
	if x != nil {
		return x.SyncTime
	}
	return 0
}

// SyncMessagesRequest 消息补齐请求
type SyncMessagesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationSeqs []*ConversationSeq     `protobuf:"bytes,2,rep,name=conversation_seqs,json=conversationSeqs,proto3" json:"conversation_seqs,omitempty"`
	// 每个会话最多返回的消息数，默认 50
	LimitPerConversation int32 `protobuf:"varint,3,opt,name=limit_per_conversation,json=limitPerConversation,proto3" json:"limit_per_conversation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SyncMessagesRequest) Reset() {
	*x = SyncMessagesRequest{}
	mi := &file_sync_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessagesRequest) ProtoMessage() {}

func (x *SyncMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessagesRequest.ProtoReflect.Descriptor instead.
func (*SyncMessagesRequest) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{7}
}

func (x *SyncMessagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SyncMessagesRequest) GetConversationSeqs() []*ConversationSeq {
	if x != nil {
		return x.ConversationSeqs
	}
	return nil
}

func (x *SyncMessagesRequest) GetLimitPerConversation() int32 {
	if x != nil {
		return x.LimitPerConversation
	}
	return 0
}

// SyncMessagesResponse 消息补齐响应
type SyncMessagesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Conversations []*ConversationMessages `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMessagesResponse) Reset() {
	*x = SyncMessagesResponse{}
	mi := &file_sync_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessagesResponse) ProtoMessage() {}

func (x *SyncMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessagesResponse.ProtoReflect.Descriptor instead.
func (*SyncMessagesResponse) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{8}
}

func (x *SyncMessagesResponse) GetConversations() []*ConversationMessages {
	if x != nil {
		return x.Conversations
	}
	return nil
}

var File_sync_sync_proto protoreflect.FileDescriptor

const file_sync_sync_proto_rawDesc = "" +
	"\n" +
	"\x0fsync/sync.proto\x12\fanychat.sync\x1a\x13friend/friend.proto\x1a\x11group/group.proto\x1a\x15session/session.proto\x1a\x15message/message.proto\"\x82\x01\n" +
	"\x0fConversationSeq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12+\n" +
	"\x11conversation_type\x18\x02 \x01(\tR\x10conversationType\x12\x19\n" +
	"\blast_seq\x18\x03 \x01(\x03R\alastSeq\"\x98\x01\n" +
	"\vSyncRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0elast_sync_time\x18\x02 \x01(\x03R\flastSyncTime\x12J\n" +
	"\x11conversation_seqs\x18\x03 \x03(\v2\x1d.anychat.sync.ConversationSeqR\x10conversationSeqs\"X\n" +
	"\x0eSyncFriendData\x120\n" +
	"\afriends\x18\x01 \x03(\v2\x16.anychat.friend.FriendR\afriends\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"W\n" +
	"\rSyncGroupData\x120\n" +
	"\x06groups\x18\x01 \x03(\v2\x18.anychat.group.GroupInfoR\x06groups\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"b\n" +
	"\x0fSyncSessionData\x124\n" +
	"\bsessions\x18\x01 \x03(\v2\x18.anychat.session.SessionR\bsessions\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\xbd\x01\n" +
	"\x14ConversationMessages\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12+\n" +
	"\x11conversation_type\x18\x02 \x01(\tR\x10conversationType\x124\n" +
	"\bmessages\x18\x03 \x03(\v2\x18.anychat.message.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\x9d\x02\n" +
	"\fSyncResponse\x126\n" +
	"\afriends\x18\x01 \x01(\v2\x1c.anychat.sync.SyncFriendDataR\afriends\x123\n" +
	"\x06groups\x18\x02 \x01(\v2\x1b.anychat.sync.SyncGroupDataR\x06groups\x129\n" +
	"\bsessions\x18\x03 \x01(\v2\x1d.anychat.sync.SyncSessionDataR\bsessions\x12H\n" +
	"\rconversations\x18\x04 \x03(\v2\".anychat.sync.ConversationMessagesR\rconversations\x12\x1b\n" +
	"\tsync_time\x18\x05 \x01(\x03R\bsyncTime\"\xb0\x01\n" +
	"\x13SyncMessagesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12J\n" +
	"\x11conversation_seqs\x18\x02 \x03(\v2\x1d.anychat.sync.ConversationSeqR\x10conversationSeqs\x124\n" +
	"\x16limit_per_conversation\x18\x03 \x01(\x05R\x14limitPerConversation\"`\n" +
	"\x14SyncMessagesResponse\x12H\n" +
	"\rconversations\x18\x01 \x03(\v2\".anychat.sync.ConversationMessagesR\rconversations2\xa3\x01\n" +
	"\vSyncService\x12=\n" +
	"\x04Sync\x12\x19.anychat.sync.SyncRequest\x1a\x1a.anychat.sync.SyncResponse\x12U\n" +
	"\fSyncMessages\x12!.anychat.sync.SyncMessagesRequest\x1a\".anychat.sync.SyncMessagesResponseB1Z/github.com/anychat/server/api/proto/sync;syncpbb\x06proto3"

var (
	file_sync_sync_proto_rawDescOnce sync.Once
	file_sync_sync_proto_rawDescData []byte
)

func file_sync_sync_proto_rawDescGZIP() []byte {
	file_sync_sync_proto_rawDescOnce.Do(func() {
		file_sync_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_sync_proto_rawDesc), len(file_sync_sync_proto_rawDesc)))
	})
	return file_sync_sync_proto_rawDescData
}

var file_sync_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sync_sync_proto_goTypes = []any{
	(*ConversationSeq)(nil),      // 0: anychat.sync.ConversationSeq
	(*SyncRequest)(nil),          // 1: anychat.sync.SyncRequest
	(*SyncFriendData)(nil),       // 2: anychat.sync.SyncFriendData
	(*SyncGroupData)(nil),        // 3: anychat.sync.SyncGroupData
	(*SyncSessionData)(nil),      // 4: anychat.sync.SyncSessionData
	(*ConversationMessages)(nil), // 5: anychat.sync.ConversationMessages
	(*SyncResponse)(nil),         // 6: anychat.sync.SyncResponse
	(*SyncMessagesRequest)(nil),  // 7: anychat.sync.SyncMessagesRequest
	(*SyncMessagesResponse)(nil), // 8: anychat.sync.SyncMessagesResponse
	(*friend.Friend)(nil),        // 9: anychat.friend.Friend
	(*group.GroupInfo)(nil),      // 10: anychat.group.GroupInfo
	(*session.Session)(nil),      // 11: anychat.session.Session
	(*message.Message)(nil),      // 12: anychat.message.Message
}
var file_sync_sync_proto_depIdxs = []int32{
	0,  // 0: anychat.sync.SyncRequest.conversation_seqs:type_name -> anychat.sync.ConversationSeq
	9,  // 1: anychat.sync.SyncFriendData.friends:type_name -> anychat.friend.Friend
	10, // 2: anychat.sync.SyncGroupData.groups:type_name -> anychat.group.GroupInfo
	11, // 3: anychat.sync.SyncSessionData.sessions:type_name -> anychat.session.Session
	12, // 4: anychat.sync.ConversationMessages.messages:type_name -> anychat.message.Message
	2,  // 5: anychat.sync.SyncResponse.friends:type_name -> anychat.sync.SyncFriendData
	3,  // 6: anychat.sync.SyncResponse.groups:type_name -> anychat.sync.SyncGroupData
	4,  // 7: anychat.sync.SyncResponse.sessions:type_name -> anychat.sync.SyncSessionData
	5,  // 8: anychat.sync.SyncResponse.conversations:type_name -> anychat.sync.ConversationMessages
	0,  // 9: anychat.sync.SyncMessagesRequest.conversation_seqs:type_name -> anychat.sync.ConversationSeq
	5,  // 10: anychat.sync.SyncMessagesResponse.conversations:type_name -> anychat.sync.ConversationMessages
	1,  // 11: anychat.sync.SyncService.Sync:input_type -> anychat.sync.SyncRequest
	7,  // 12: anychat.sync.SyncService.SyncMessages:input_type -> anychat.sync.SyncMessagesRequest
	6,  // 13: anychat.sync.SyncService.Sync:output_type -> anychat.sync.SyncResponse
	8,  // 14: anychat.sync.SyncService.SyncMessages:output_type -> anychat.sync.SyncMessagesResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_sync_sync_proto_init() }
func file_sync_sync_proto_init() {
	if File_sync_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_sync_proto_rawDesc), len(file_sync_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_sync_proto_goTypes,
		DependencyIndexes: file_sync_sync_proto_depIdxs,
		MessageInfos:      file_sync_sync_proto_msgTypes,
	}.Build()
	File_sync_sync_proto = out.File
	file_sync_sync_proto_goTypes = nil
	file_sync_sync_proto_depIdxs = nil
}
