// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: friend/friend.proto

package friendpb

import (
	common "github.com/anychat/server/api/proto/common"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Friend 好友信息
type Friend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Remark        string                 `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UserInfo      *common.UserInfo       `protobuf:"bytes,5,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"` // 用户基本信息（从user-service获取）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Friend) Reset() {
	*x = Friend{}
	mi := &file_friend_friend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{0}
}

func (x *Friend) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Friend) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Friend) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Friend) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Friend) GetUserInfo() *common.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

// FriendRequest 好友申请
type FriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromUserId    string                 `protobuf:"bytes,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      string                 `protobuf:"bytes,3,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"` // search/qrcode/group/contacts
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // pending/accepted/rejected/expired
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FromUserInfo  *common.UserInfo       `protobuf:"bytes,8,opt,name=from_user_info,json=fromUserInfo,proto3" json:"from_user_info,omitempty"` // 申请人信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_friend_friend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{1}
}

func (x *FriendRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FriendRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *FriendRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *FriendRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FriendRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FriendRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FriendRequest) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FriendRequest) GetFromUserInfo() *common.UserInfo {
	if x != nil {
		return x.FromUserInfo
	}
	return nil
}

// BlacklistItem 黑名单项
type BlacklistItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BlockedUserId   string                 `protobuf:"bytes,3,opt,name=blocked_user_id,json=blockedUserId,proto3" json:"blocked_user_id,omitempty"`
	CreatedAt       *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	BlockedUserInfo *common.UserInfo       `protobuf:"bytes,5,opt,name=blocked_user_info,json=blockedUserInfo,proto3" json:"blocked_user_info,omitempty"` // 被拉黑用户信息
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlacklistItem) Reset() {
	*x = BlacklistItem{}
	mi := &file_friend_friend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlacklistItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistItem) ProtoMessage() {}

func (x *BlacklistItem) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistItem.ProtoReflect.Descriptor instead.
func (*BlacklistItem) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{2}
}

func (x *BlacklistItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BlacklistItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BlacklistItem) GetBlockedUserId() string {
	if x != nil {
		return x.BlockedUserId
	}
	return ""
}

func (x *BlacklistItem) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BlacklistItem) GetBlockedUserInfo() *common.UserInfo {
	if x != nil {
		return x.BlockedUserInfo
	}
	return nil
}

// GetFriendListRequest 获取好友列表请求
type GetFriendListRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastUpdateTime *int64                 `protobuf:"varint,2,opt,name=last_update_time,json=lastUpdateTime,proto3,oneof" json:"last_update_time,omitempty"` // 增量同步
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFriendListRequest) Reset() {
	*x = GetFriendListRequest{}
	mi := &file_friend_friend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendListRequest) ProtoMessage() {}

func (x *GetFriendListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendListRequest.ProtoReflect.Descriptor instead.
func (*GetFriendListRequest) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{3}
}

func (x *GetFriendListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFriendListRequest) GetLastUpdateTime() int64 {
	if x != nil && x.LastUpdateTime != nil {
		return *x.LastUpdateTime
	}
	return 0
}

// GetFriendListResponse 获取好友列表响应
type GetFriendListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*Friend              `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendListResponse) Reset() {
	*x = GetFriendListResponse{}
	mi := &file_friend_friend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendListResponse) ProtoMessage() {}

func (x *GetFriendListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendListResponse.ProtoReflect.Descriptor instead.
func (*GetFriendListResponse) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{4}
}

func (x *GetFriendListResponse) GetFriends() []*Friend {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *GetFriendListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// SendFriendRequestRequest 发送好友申请请求
type SendFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      string                 `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestRequest) Reset() {
	*x = SendFriendRequestRequest{}
	mi := &file_friend_friend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestRequest) ProtoMessage() {}

func (x *SendFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*SendFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{5}
}

func (x *SendFriendRequestRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *SendFriendRequestRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *SendFriendRequestRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendFriendRequestRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// SendFriendRequestResponse 发送好友申请响应
type SendFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AutoAccepted  bool                   `protobuf:"varint,2,opt,name=auto_accepted,json=autoAccepted,proto3" json:"auto_accepted,omitempty"` // 是否自动通过
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestResponse) Reset() {
	*x = SendFriendRequestResponse{}
	mi := &file_friend_friend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestResponse) ProtoMessage() {}

func (x *SendFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*SendFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{6}
}

func (x *SendFriendRequestResponse) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *SendFriendRequestResponse) GetAutoAccepted() bool {
	if x != nil {
		return x.AutoAccepted
	}
	return false
}

// HandleFriendRequestRequest 处理好友申请请求
type HandleFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 当前用户ID（申请接收方）
	RequestId     int64                  `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // accept/reject
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleFriendRequestRequest) Reset() {
	*x = HandleFriendRequestRequest{}
	mi := &file_friend_friend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendRequestRequest) ProtoMessage() {}

func (x *HandleFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*HandleFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{7}
}

func (x *HandleFriendRequestRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HandleFriendRequestRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *HandleFriendRequestRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// GetFriendRequestsRequest 获取好友申请列表请求
type GetFriendRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // received/sent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendRequestsRequest) Reset() {
	*x = GetFriendRequestsRequest{}
	mi := &file_friend_friend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendRequestsRequest) ProtoMessage() {}

func (x *GetFriendRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetFriendRequestsRequest) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{8}
}

func (x *GetFriendRequestsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFriendRequestsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// GetFriendRequestsResponse 获取好友申请列表响应
type GetFriendRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*FriendRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendRequestsResponse) Reset() {
	*x = GetFriendRequestsResponse{}
	mi := &file_friend_friend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendRequestsResponse) ProtoMessage() {}

func (x *GetFriendRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetFriendRequestsResponse) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{9}
}

func (x *GetFriendRequestsResponse) GetRequests() []*FriendRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *GetFriendRequestsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// DeleteFriendRequest 删除好友请求
type DeleteFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      string                 `protobuf:"bytes,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendRequest) Reset() {
	*x = DeleteFriendRequest{}
	mi := &file_friend_friend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendRequest) ProtoMessage() {}

func (x *DeleteFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendRequest.ProtoReflect.Descriptor instead.
func (*DeleteFriendRequest) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteFriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteFriendRequest) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

// UpdateRemarkRequest 更新备注请求
type UpdateRemarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      string                 `protobuf:"bytes,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRemarkRequest) Reset() {
	*x = UpdateRemarkRequest{}
	mi := &file_friend_friend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRemarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRemarkRequest) ProtoMessage() {}

func (x *UpdateRemarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRemarkRequest.ProtoReflect.Descriptor instead.
func (*UpdateRemarkRequest) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateRemarkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateRemarkRequest) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *UpdateRemarkRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// AddToBlacklistRequest 添加黑名单请求
type AddToBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BlockedUserId string                 `protobuf:"bytes,2,opt,name=blocked_user_id,json=blockedUserId,proto3" json:"blocked_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToBlacklistRequest) Reset() {
	*x = AddToBlacklistRequest{}
	mi := &file_friend_friend_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToBlacklistRequest) ProtoMessage() {}

func (x *AddToBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToBlacklistRequest.ProtoReflect.Descriptor instead.
func (*AddToBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{12}
}

func (x *AddToBlacklistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddToBlacklistRequest) GetBlockedUserId() string {
	if x != nil {
		return x.BlockedUserId
	}
	return ""
}

// RemoveFromBlacklistRequest 移除黑名单请求
type RemoveFromBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BlockedUserId string                 `protobuf:"bytes,2,opt,name=blocked_user_id,json=blockedUserId,proto3" json:"blocked_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromBlacklistRequest) Reset() {
	*x = RemoveFromBlacklistRequest{}
	mi := &file_friend_friend_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromBlacklistRequest) ProtoMessage() {}

func (x *RemoveFromBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromBlacklistRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveFromBlacklistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveFromBlacklistRequest) GetBlockedUserId() string {
	if x != nil {
		return x.BlockedUserId
	}
	return ""
}

// GetBlacklistRequest 获取黑名单请求
type GetBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlacklistRequest) Reset() {
	*x = GetBlacklistRequest{}
	mi := &file_friend_friend_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlacklistRequest) ProtoMessage() {}

func (x *GetBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlacklistRequest.ProtoReflect.Descriptor instead.
func (*GetBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{14}
}

func (x *GetBlacklistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetBlacklistResponse 获取黑名单响应
type GetBlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BlacklistItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlacklistResponse) Reset() {
	*x = GetBlacklistResponse{}
	mi := &file_friend_friend_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlacklistResponse) ProtoMessage() {}

func (x *GetBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlacklistResponse.ProtoReflect.Descriptor instead.
func (*GetBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{15}
}

func (x *GetBlacklistResponse) GetItems() []*BlacklistItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetBlacklistResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// IsFriendRequest 检查好友关系请求
type IsFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      string                 `protobuf:"bytes,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFriendRequest) Reset() {
	*x = IsFriendRequest{}
	mi := &file_friend_friend_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFriendRequest) ProtoMessage() {}

func (x *IsFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFriendRequest.ProtoReflect.Descriptor instead.
func (*IsFriendRequest) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{16}
}

func (x *IsFriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IsFriendRequest) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

// IsFriendResponse 检查好友关系响应
type IsFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFriend      bool                   `protobuf:"varint,1,opt,name=is_friend,json=isFriend,proto3" json:"is_friend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFriendResponse) Reset() {
	*x = IsFriendResponse{}
	mi := &file_friend_friend_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFriendResponse) ProtoMessage() {}

func (x *IsFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFriendResponse.ProtoReflect.Descriptor instead.
func (*IsFriendResponse) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{17}
}

func (x *IsFriendResponse) GetIsFriend() bool {
	if x != nil {
		return x.IsFriend
	}
	return false
}

// IsBlockedRequest 检查黑名单请求
type IsBlockedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetUserId  string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsBlockedRequest) Reset() {
	*x = IsBlockedRequest{}
	mi := &file_friend_friend_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsBlockedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsBlockedRequest) ProtoMessage() {}

func (x *IsBlockedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsBlockedRequest.ProtoReflect.Descriptor instead.
func (*IsBlockedRequest) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{18}
}

func (x *IsBlockedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IsBlockedRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

// IsBlockedResponse 检查黑名单响应
type IsBlockedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsBlocked     bool                   `protobuf:"varint,1,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsBlockedResponse) Reset() {
	*x = IsBlockedResponse{}
	mi := &file_friend_friend_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsBlockedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsBlockedResponse) ProtoMessage() {}

func (x *IsBlockedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsBlockedResponse.ProtoReflect.Descriptor instead.
func (*IsBlockedResponse) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{19}
}

func (x *IsBlockedResponse) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

// BatchCheckFriendRequest 批量检查好友关系请求
type BatchCheckFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendIds     []string               `protobuf:"bytes,2,rep,name=friend_ids,json=friendIds,proto3" json:"friend_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckFriendRequest) Reset() {
	*x = BatchCheckFriendRequest{}
	mi := &file_friend_friend_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckFriendRequest) ProtoMessage() {}

func (x *BatchCheckFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckFriendRequest.ProtoReflect.Descriptor instead.
func (*BatchCheckFriendRequest) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{20}
}

func (x *BatchCheckFriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BatchCheckFriendRequest) GetFriendIds() []string {
	if x != nil {
		return x.FriendIds
	}
	return nil
}

// BatchCheckFriendResponse 批量检查好友关系响应
type BatchCheckFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       map[string]bool        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // friend_id -> is_friend
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckFriendResponse) Reset() {
	*x = BatchCheckFriendResponse{}
	mi := &file_friend_friend_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckFriendResponse) ProtoMessage() {}

func (x *BatchCheckFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_friend_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckFriendResponse.ProtoReflect.Descriptor instead.
func (*BatchCheckFriendResponse) Descriptor() ([]byte, []int) {
	return file_friend_friend_proto_rawDescGZIP(), []int{21}
}

func (x *BatchCheckFriendResponse) GetResults() map[string]bool {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_friend_friend_proto protoreflect.FileDescriptor

const file_friend_friend_proto_rawDesc = "" +
	"\n" +
	"\x13friend/friend.proto\x12\x0eanychat.friend\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xe6\x01\n" +
	"\x06Friend\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06remark\x18\x02 \x01(\tR\x06remark\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x125\n" +
	"\tuser_info\x18\x05 \x01(\v2\x18.anychat.common.UserInfoR\buserInfo\"\xa4\x02\n" +
	"\rFriendRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x03 \x01(\tR\btoUserId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\x0efrom_user_info\x18\b \x01(\v2\x18.anychat.common.UserInfoR\ffromUserInfo\"\xe1\x01\n" +
	"\rBlacklistItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12&\n" +
	"\x0fblocked_user_id\x18\x03 \x01(\tR\rblockedUserId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12D\n" +
	"\x11blocked_user_info\x18\x05 \x01(\v2\x18.anychat.common.UserInfoR\x0fblockedUserInfo\"s\n" +
	"\x14GetFriendListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12-\n" +
	"\x10last_update_time\x18\x02 \x01(\x03H\x00R\x0elastUpdateTime\x88\x01\x01B\x13\n" +
	"\x11_last_update_time\"_\n" +
	"\x15GetFriendListResponse\x120\n" +
	"\afriends\x18\x01 \x03(\v2\x16.anychat.friend.FriendR\afriends\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x8c\x01\n" +
	"\x18SendFriendRequestRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\tR\btoUserId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"_\n" +
	"\x19SendFriendRequestResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\x12#\n" +
	"\rauto_accepted\x18\x02 \x01(\bR\fautoAccepted\"l\n" +
	"\x1aHandleFriendRequestRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x03R\trequestId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"G\n" +
	"\x18GetFriendRequestsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"l\n" +
	"\x19GetFriendRequestsResponse\x129\n" +
	"\brequests\x18\x01 \x03(\v2\x1d.anychat.friend.FriendRequestR\brequests\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"K\n" +
	"\x13DeleteFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\tR\bfriendId\"c\n" +
	"\x13UpdateRemarkRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\tR\bfriendId\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\"X\n" +
	"\x15AddToBlacklistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x0fblocked_user_id\x18\x02 \x01(\tR\rblockedUserId\"]\n" +
	"\x1aRemoveFromBlacklistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x0fblocked_user_id\x18\x02 \x01(\tR\rblockedUserId\".\n" +
	"\x13GetBlacklistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"a\n" +
	"\x14GetBlacklistResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.anychat.friend.BlacklistItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"G\n" +
	"\x0fIsFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\tR\bfriendId\"/\n" +
	"\x10IsFriendResponse\x12\x1b\n" +
	"\tis_friend\x18\x01 \x01(\bR\bisFriend\"Q\n" +
	"\x10IsBlockedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\"2\n" +
	"\x11IsBlockedResponse\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\x01 \x01(\bR\tisBlocked\"Q\n" +
	"\x17BatchCheckFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"friend_ids\x18\x02 \x03(\tR\tfriendIds\"\xa7\x01\n" +
	"\x18BatchCheckFriendResponse\x12O\n" +
	"\aresults\x18\x01 \x03(\v25.anychat.friend.BatchCheckFriendResponse.ResultsEntryR\aresults\x1a:\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x012\xc0\b\n" +
	"\rFriendService\x12\\\n" +
	"\rGetFriendList\x12$.anychat.friend.GetFriendListRequest\x1a%.anychat.friend.GetFriendListResponse\x12h\n" +
	"\x11SendFriendRequest\x12(.anychat.friend.SendFriendRequestRequest\x1a).anychat.friend.SendFriendRequestResponse\x12X\n" +
	"\x13HandleFriendRequest\x12*.anychat.friend.HandleFriendRequestRequest\x1a\x15.anychat.common.Empty\x12h\n" +
	"\x11GetFriendRequests\x12(.anychat.friend.GetFriendRequestsRequest\x1a).anychat.friend.GetFriendRequestsResponse\x12J\n" +
	"\fDeleteFriend\x12#.anychat.friend.DeleteFriendRequest\x1a\x15.anychat.common.Empty\x12J\n" +
	"\fUpdateRemark\x12#.anychat.friend.UpdateRemarkRequest\x1a\x15.anychat.common.Empty\x12N\n" +
	"\x0eAddToBlacklist\x12%.anychat.friend.AddToBlacklistRequest\x1a\x15.anychat.common.Empty\x12X\n" +
	"\x13RemoveFromBlacklist\x12*.anychat.friend.RemoveFromBlacklistRequest\x1a\x15.anychat.common.Empty\x12Y\n" +
	"\fGetBlacklist\x12#.anychat.friend.GetBlacklistRequest\x1a$.anychat.friend.GetBlacklistResponse\x12M\n" +
	"\bIsFriend\x12\x1f.anychat.friend.IsFriendRequest\x1a .anychat.friend.IsFriendResponse\x12P\n" +
	"\tIsBlocked\x12 .anychat.friend.IsBlockedRequest\x1a!.anychat.friend.IsBlockedResponse\x12e\n" +
	"\x10BatchCheckFriend\x12'.anychat.friend.BatchCheckFriendRequest\x1a(.anychat.friend.BatchCheckFriendResponseB5Z3github.com/anychat/server/api/proto/friend;friendpbb\x06proto3"

var (
	file_friend_friend_proto_rawDescOnce sync.Once
	file_friend_friend_proto_rawDescData []byte
)

func file_friend_friend_proto_rawDescGZIP() []byte {
	file_friend_friend_proto_rawDescOnce.Do(func() {
		file_friend_friend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_friend_friend_proto_rawDesc), len(file_friend_friend_proto_rawDesc)))
	})
	return file_friend_friend_proto_rawDescData
}

var file_friend_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_friend_friend_proto_goTypes = []any{
	(*Friend)(nil),                     // 0: anychat.friend.Friend
	(*FriendRequest)(nil),              // 1: anychat.friend.FriendRequest
	(*BlacklistItem)(nil),              // 2: anychat.friend.BlacklistItem
	(*GetFriendListRequest)(nil),       // 3: anychat.friend.GetFriendListRequest
	(*GetFriendListResponse)(nil),      // 4: anychat.friend.GetFriendListResponse
	(*SendFriendRequestRequest)(nil),   // 5: anychat.friend.SendFriendRequestRequest
	(*SendFriendRequestResponse)(nil),  // 6: anychat.friend.SendFriendRequestResponse
	(*HandleFriendRequestRequest)(nil), // 7: anychat.friend.HandleFriendRequestRequest
	(*GetFriendRequestsRequest)(nil),   // 8: anychat.friend.GetFriendRequestsRequest
	(*GetFriendRequestsResponse)(nil),  // 9: anychat.friend.GetFriendRequestsResponse
	(*DeleteFriendRequest)(nil),        // 10: anychat.friend.DeleteFriendRequest
	(*UpdateRemarkRequest)(nil),        // 11: anychat.friend.UpdateRemarkRequest
	(*AddToBlacklistRequest)(nil),      // 12: anychat.friend.AddToBlacklistRequest
	(*RemoveFromBlacklistRequest)(nil), // 13: anychat.friend.RemoveFromBlacklistRequest
	(*GetBlacklistRequest)(nil),        // 14: anychat.friend.GetBlacklistRequest
	(*GetBlacklistResponse)(nil),       // 15: anychat.friend.GetBlacklistResponse
	(*IsFriendRequest)(nil),            // 16: anychat.friend.IsFriendRequest
	(*IsFriendResponse)(nil),           // 17: anychat.friend.IsFriendResponse
	(*IsBlockedRequest)(nil),           // 18: anychat.friend.IsBlockedRequest
	(*IsBlockedResponse)(nil),          // 19: anychat.friend.IsBlockedResponse
	(*BatchCheckFriendRequest)(nil),    // 20: anychat.friend.BatchCheckFriendRequest
	(*BatchCheckFriendResponse)(nil),   // 21: anychat.friend.BatchCheckFriendResponse
	nil,                                // 22: anychat.friend.BatchCheckFriendResponse.ResultsEntry
	(*timestamp.Timestamp)(nil),        // 23: google.protobuf.Timestamp
	(*common.UserInfo)(nil),            // 24: anychat.common.UserInfo
	(*common.Empty)(nil),               // 25: anychat.common.Empty
}
var file_friend_friend_proto_depIdxs = []int32{
	23, // 0: anychat.friend.Friend.created_at:type_name -> google.protobuf.Timestamp
	23, // 1: anychat.friend.Friend.updated_at:type_name -> google.protobuf.Timestamp
	24, // 2: anychat.friend.Friend.user_info:type_name -> anychat.common.UserInfo
	23, // 3: anychat.friend.FriendRequest.created_at:type_name -> google.protobuf.Timestamp
	24, // 4: anychat.friend.FriendRequest.from_user_info:type_name -> anychat.common.UserInfo
	23, // 5: anychat.friend.BlacklistItem.created_at:type_name -> google.protobuf.Timestamp
	24, // 6: anychat.friend.BlacklistItem.blocked_user_info:type_name -> anychat.common.UserInfo
	0,  // 7: anychat.friend.GetFriendListResponse.friends:type_name -> anychat.friend.Friend
	1,  // 8: anychat.friend.GetFriendRequestsResponse.requests:type_name -> anychat.friend.FriendRequest
	2,  // 9: anychat.friend.GetBlacklistResponse.items:type_name -> anychat.friend.BlacklistItem
	22, // 10: anychat.friend.BatchCheckFriendResponse.results:type_name -> anychat.friend.BatchCheckFriendResponse.ResultsEntry
	3,  // 11: anychat.friend.FriendService.GetFriendList:input_type -> anychat.friend.GetFriendListRequest
	5,  // 12: anychat.friend.FriendService.SendFriendRequest:input_type -> anychat.friend.SendFriendRequestRequest
	7,  // 13: anychat.friend.FriendService.HandleFriendRequest:input_type -> anychat.friend.HandleFriendRequestRequest
	8,  // 14: anychat.friend.FriendService.GetFriendRequests:input_type -> anychat.friend.GetFriendRequestsRequest
	10, // 15: anychat.friend.FriendService.DeleteFriend:input_type -> anychat.friend.DeleteFriendRequest
	11, // 16: anychat.friend.FriendService.UpdateRemark:input_type -> anychat.friend.UpdateRemarkRequest
	12, // 17: anychat.friend.FriendService.AddToBlacklist:input_type -> anychat.friend.AddToBlacklistRequest
	13, // 18: anychat.friend.FriendService.RemoveFromBlacklist:input_type -> anychat.friend.RemoveFromBlacklistRequest
	14, // 19: anychat.friend.FriendService.GetBlacklist:input_type -> anychat.friend.GetBlacklistRequest
	16, // 20: anychat.friend.FriendService.IsFriend:input_type -> anychat.friend.IsFriendRequest
	18, // 21: anychat.friend.FriendService.IsBlocked:input_type -> anychat.friend.IsBlockedRequest
	20, // 22: anychat.friend.FriendService.BatchCheckFriend:input_type -> anychat.friend.BatchCheckFriendRequest
	4,  // 23: anychat.friend.FriendService.GetFriendList:output_type -> anychat.friend.GetFriendListResponse
	6,  // 24: anychat.friend.FriendService.SendFriendRequest:output_type -> anychat.friend.SendFriendRequestResponse
	25, // 25: anychat.friend.FriendService.HandleFriendRequest:output_type -> anychat.common.Empty
	9,  // 26: anychat.friend.FriendService.GetFriendRequests:output_type -> anychat.friend.GetFriendRequestsResponse
	25, // 27: anychat.friend.FriendService.DeleteFriend:output_type -> anychat.common.Empty
	25, // 28: anychat.friend.FriendService.UpdateRemark:output_type -> anychat.common.Empty
	25, // 29: anychat.friend.FriendService.AddToBlacklist:output_type -> anychat.common.Empty
	25, // 30: anychat.friend.FriendService.RemoveFromBlacklist:output_type -> anychat.common.Empty
	15, // 31: anychat.friend.FriendService.GetBlacklist:output_type -> anychat.friend.GetBlacklistResponse
	17, // 32: anychat.friend.FriendService.IsFriend:output_type -> anychat.friend.IsFriendResponse
	19, // 33: anychat.friend.FriendService.IsBlocked:output_type -> anychat.friend.IsBlockedResponse
	21, // 34: anychat.friend.FriendService.BatchCheckFriend:output_type -> anychat.friend.BatchCheckFriendResponse
	23, // [23:35] is the sub-list for method output_type
	11, // [11:23] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_friend_friend_proto_init() }
func file_friend_friend_proto_init() {
	if File_friend_friend_proto != nil {
		return
	}
	file_friend_friend_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_friend_friend_proto_rawDesc), len(file_friend_friend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_friend_friend_proto_goTypes,
		DependencyIndexes: file_friend_friend_proto_depIdxs,
		MessageInfos:      file_friend_friend_proto_msgTypes,
	}.Build()
	File_friend_friend_proto = out.File
	file_friend_friend_proto_goTypes = nil
	file_friend_friend_proto_depIdxs = nil
}
