// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: session/session.proto

package sessionpb

import (
	context "context"
	common "github.com/anychat/server/api/proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionService_GetSessions_FullMethodName           = "/anychat.session.SessionService/GetSessions"
	SessionService_GetSession_FullMethodName            = "/anychat.session.SessionService/GetSession"
	SessionService_CreateOrUpdateSession_FullMethodName = "/anychat.session.SessionService/CreateOrUpdateSession"
	SessionService_DeleteSession_FullMethodName         = "/anychat.session.SessionService/DeleteSession"
	SessionService_SetPinned_FullMethodName             = "/anychat.session.SessionService/SetPinned"
	SessionService_SetMuted_FullMethodName              = "/anychat.session.SessionService/SetMuted"
	SessionService_ClearUnread_FullMethodName           = "/anychat.session.SessionService/ClearUnread"
	SessionService_GetTotalUnread_FullMethodName        = "/anychat.session.SessionService/GetTotalUnread"
	SessionService_IncrUnread_FullMethodName            = "/anychat.session.SessionService/IncrUnread"
)

// SessionServiceClient is the client API for SessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SessionService 会话管理服务
type SessionServiceClient interface {
	// GetSessions 获取用户会话列表（支持增量同步）
	GetSessions(ctx context.Context, in *GetSessionsRequest, opts ...grpc.CallOption) (*GetSessionsResponse, error)
	// GetSession 获取单个会话详情
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error)
	// CreateOrUpdateSession 创建或更新会话（消息到达时由消息服务调用）
	CreateOrUpdateSession(ctx context.Context, in *CreateOrUpdateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	// DeleteSession 删除会话
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// SetPinned 设置会话置顶/取消置顶
	SetPinned(ctx context.Context, in *SetPinnedRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// SetMuted 设置会话免打扰/取消免打扰
	SetMuted(ctx context.Context, in *SetMutedRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// ClearUnread 清除会话未读数（标记已读）
	ClearUnread(ctx context.Context, in *ClearUnreadRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// GetTotalUnread 获取用户所有会话的总未读数
	GetTotalUnread(ctx context.Context, in *GetTotalUnreadRequest, opts ...grpc.CallOption) (*GetTotalUnreadResponse, error)
	// IncrUnread 增加会话未读数（消息到达时由消息服务调用）
	IncrUnread(ctx context.Context, in *IncrUnreadRequest, opts ...grpc.CallOption) (*common.Empty, error)
}

type sessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionServiceClient(cc grpc.ClientConnInterface) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) GetSessions(ctx context.Context, in *GetSessionsRequest, opts ...grpc.CallOption) (*GetSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionsResponse)
	err := c.cc.Invoke(ctx, SessionService_GetSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, SessionService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) CreateOrUpdateSession(ctx context.Context, in *CreateOrUpdateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, SessionService_CreateOrUpdateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, SessionService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) SetPinned(ctx context.Context, in *SetPinnedRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, SessionService_SetPinned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) SetMuted(ctx context.Context, in *SetMutedRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, SessionService_SetMuted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) ClearUnread(ctx context.Context, in *ClearUnreadRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, SessionService_ClearUnread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) GetTotalUnread(ctx context.Context, in *GetTotalUnreadRequest, opts ...grpc.CallOption) (*GetTotalUnreadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTotalUnreadResponse)
	err := c.cc.Invoke(ctx, SessionService_GetTotalUnread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) IncrUnread(ctx context.Context, in *IncrUnreadRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, SessionService_IncrUnread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServiceServer is the server API for SessionService service.
// All implementations must embed UnimplementedSessionServiceServer
// for forward compatibility.
//
// SessionService 会话管理服务
type SessionServiceServer interface {
	// GetSessions 获取用户会话列表（支持增量同步）
	GetSessions(context.Context, *GetSessionsRequest) (*GetSessionsResponse, error)
	// GetSession 获取单个会话详情
	GetSession(context.Context, *GetSessionRequest) (*Session, error)
	// CreateOrUpdateSession 创建或更新会话（消息到达时由消息服务调用）
	CreateOrUpdateSession(context.Context, *CreateOrUpdateSessionRequest) (*Session, error)
	// DeleteSession 删除会话
	DeleteSession(context.Context, *DeleteSessionRequest) (*common.Empty, error)
	// SetPinned 设置会话置顶/取消置顶
	SetPinned(context.Context, *SetPinnedRequest) (*common.Empty, error)
	// SetMuted 设置会话免打扰/取消免打扰
	SetMuted(context.Context, *SetMutedRequest) (*common.Empty, error)
	// ClearUnread 清除会话未读数（标记已读）
	ClearUnread(context.Context, *ClearUnreadRequest) (*common.Empty, error)
	// GetTotalUnread 获取用户所有会话的总未读数
	GetTotalUnread(context.Context, *GetTotalUnreadRequest) (*GetTotalUnreadResponse, error)
	// IncrUnread 增加会话未读数（消息到达时由消息服务调用）
	IncrUnread(context.Context, *IncrUnreadRequest) (*common.Empty, error)
	mustEmbedUnimplementedSessionServiceServer()
}

// UnimplementedSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionServiceServer struct{}

func (UnimplementedSessionServiceServer) GetSessions(context.Context, *GetSessionsRequest) (*GetSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessions not implemented")
}
func (UnimplementedSessionServiceServer) GetSession(context.Context, *GetSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedSessionServiceServer) CreateOrUpdateSession(context.Context, *CreateOrUpdateSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrUpdateSession not implemented")
}
func (UnimplementedSessionServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedSessionServiceServer) SetPinned(context.Context, *SetPinnedRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPinned not implemented")
}
func (UnimplementedSessionServiceServer) SetMuted(context.Context, *SetMutedRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMuted not implemented")
}
func (UnimplementedSessionServiceServer) ClearUnread(context.Context, *ClearUnreadRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearUnread not implemented")
}
func (UnimplementedSessionServiceServer) GetTotalUnread(context.Context, *GetTotalUnreadRequest) (*GetTotalUnreadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTotalUnread not implemented")
}
func (UnimplementedSessionServiceServer) IncrUnread(context.Context, *IncrUnreadRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrUnread not implemented")
}
func (UnimplementedSessionServiceServer) mustEmbedUnimplementedSessionServiceServer() {}
func (UnimplementedSessionServiceServer) testEmbeddedByValue()                        {}

// UnsafeSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionServiceServer will
// result in compilation errors.
type UnsafeSessionServiceServer interface {
	mustEmbedUnimplementedSessionServiceServer()
}

func RegisterSessionServiceServer(s grpc.ServiceRegistrar, srv SessionServiceServer) {
	// If the following call panics, it indicates UnimplementedSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionService_ServiceDesc, srv)
}

func _SessionService_GetSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).GetSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_GetSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).GetSessions(ctx, req.(*GetSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_CreateOrUpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).CreateOrUpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_CreateOrUpdateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).CreateOrUpdateSession(ctx, req.(*CreateOrUpdateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_SetPinned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPinnedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).SetPinned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_SetPinned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).SetPinned(ctx, req.(*SetPinnedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_SetMuted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMutedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).SetMuted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_SetMuted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).SetMuted(ctx, req.(*SetMutedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_ClearUnread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearUnreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).ClearUnread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_ClearUnread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).ClearUnread(ctx, req.(*ClearUnreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_GetTotalUnread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTotalUnreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).GetTotalUnread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_GetTotalUnread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).GetTotalUnread(ctx, req.(*GetTotalUnreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_IncrUnread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrUnreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).IncrUnread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_IncrUnread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).IncrUnread(ctx, req.(*IncrUnreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionService_ServiceDesc is the grpc.ServiceDesc for SessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anychat.session.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSessions",
			Handler:    _SessionService_GetSessions_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _SessionService_GetSession_Handler,
		},
		{
			MethodName: "CreateOrUpdateSession",
			Handler:    _SessionService_CreateOrUpdateSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _SessionService_DeleteSession_Handler,
		},
		{
			MethodName: "SetPinned",
			Handler:    _SessionService_SetPinned_Handler,
		},
		{
			MethodName: "SetMuted",
			Handler:    _SessionService_SetMuted_Handler,
		},
		{
			MethodName: "ClearUnread",
			Handler:    _SessionService_ClearUnread_Handler,
		},
		{
			MethodName: "GetTotalUnread",
			Handler:    _SessionService_GetTotalUnread_Handler,
		},
		{
			MethodName: "IncrUnread",
			Handler:    _SessionService_IncrUnread_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session/session.proto",
}
