// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: rtc/rtc.proto

package rtcpb

import (
	common "github.com/anychat/server/api/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CallType 通话类型
type CallType int32

const (
	CallType_CALL_TYPE_AUDIO CallType = 0 // 语音通话
	CallType_CALL_TYPE_VIDEO CallType = 1 // 视频通话
)

// Enum value maps for CallType.
var (
	CallType_name = map[int32]string{
		0: "CALL_TYPE_AUDIO",
		1: "CALL_TYPE_VIDEO",
	}
	CallType_value = map[string]int32{
		"CALL_TYPE_AUDIO": 0,
		"CALL_TYPE_VIDEO": 1,
	}
)

func (x CallType) Enum() *CallType {
	p := new(CallType)
	*p = x
	return p
}

func (x CallType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallType) Descriptor() protoreflect.EnumDescriptor {
	return file_rtc_rtc_proto_enumTypes[0].Descriptor()
}

func (CallType) Type() protoreflect.EnumType {
	return &file_rtc_rtc_proto_enumTypes[0]
}

func (x CallType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallType.Descriptor instead.
func (CallType) EnumDescriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{0}
}

// CallStatus 通话状态
type CallStatus int32

const (
	CallStatus_CALL_STATUS_RINGING   CallStatus = 0 // 振铃中
	CallStatus_CALL_STATUS_CONNECTED CallStatus = 1 // 已接通
	CallStatus_CALL_STATUS_ENDED     CallStatus = 2 // 已结束
	CallStatus_CALL_STATUS_REJECTED  CallStatus = 3 // 已拒绝
	CallStatus_CALL_STATUS_MISSED    CallStatus = 4 // 未接
	CallStatus_CALL_STATUS_CANCELLED CallStatus = 5 // 已取消
)

// Enum value maps for CallStatus.
var (
	CallStatus_name = map[int32]string{
		0: "CALL_STATUS_RINGING",
		1: "CALL_STATUS_CONNECTED",
		2: "CALL_STATUS_ENDED",
		3: "CALL_STATUS_REJECTED",
		4: "CALL_STATUS_MISSED",
		5: "CALL_STATUS_CANCELLED",
	}
	CallStatus_value = map[string]int32{
		"CALL_STATUS_RINGING":   0,
		"CALL_STATUS_CONNECTED": 1,
		"CALL_STATUS_ENDED":     2,
		"CALL_STATUS_REJECTED":  3,
		"CALL_STATUS_MISSED":    4,
		"CALL_STATUS_CANCELLED": 5,
	}
)

func (x CallStatus) Enum() *CallStatus {
	p := new(CallStatus)
	*p = x
	return p
}

func (x CallStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rtc_rtc_proto_enumTypes[1].Descriptor()
}

func (CallStatus) Type() protoreflect.EnumType {
	return &file_rtc_rtc_proto_enumTypes[1]
}

func (x CallStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallStatus.Descriptor instead.
func (CallStatus) EnumDescriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{1}
}

// MeetingStatus 会议状态
type MeetingStatus int32

const (
	MeetingStatus_MEETING_STATUS_ACTIVE MeetingStatus = 0
	MeetingStatus_MEETING_STATUS_ENDED  MeetingStatus = 1
)

// Enum value maps for MeetingStatus.
var (
	MeetingStatus_name = map[int32]string{
		0: "MEETING_STATUS_ACTIVE",
		1: "MEETING_STATUS_ENDED",
	}
	MeetingStatus_value = map[string]int32{
		"MEETING_STATUS_ACTIVE": 0,
		"MEETING_STATUS_ENDED":  1,
	}
)

func (x MeetingStatus) Enum() *MeetingStatus {
	p := new(MeetingStatus)
	*p = x
	return p
}

func (x MeetingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeetingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rtc_rtc_proto_enumTypes[2].Descriptor()
}

func (MeetingStatus) Type() protoreflect.EnumType {
	return &file_rtc_rtc_proto_enumTypes[2]
}

func (x MeetingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeetingStatus.Descriptor instead.
func (MeetingStatus) EnumDescriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{2}
}

// CallSession 通话会话
type CallSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	CallerId      string                 `protobuf:"bytes,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	CalleeId      string                 `protobuf:"bytes,3,opt,name=callee_id,json=calleeId,proto3" json:"callee_id,omitempty"`
	CallType      CallType               `protobuf:"varint,4,opt,name=call_type,json=callType,proto3,enum=anychat.rtc.CallType" json:"call_type,omitempty"`
	Status        CallStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=anychat.rtc.CallStatus" json:"status,omitempty"`
	RoomName      string                 `protobuf:"bytes,6,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	StartedAt     int64                  `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"` // Unix 秒
	ConnectedAt   int64                  `protobuf:"varint,8,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	EndedAt       int64                  `protobuf:"varint,9,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	Duration      int32                  `protobuf:"varint,10,opt,name=duration,proto3" json:"duration,omitempty"` // 通话时长（秒）
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallSession) Reset() {
	*x = CallSession{}
	mi := &file_rtc_rtc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallSession) ProtoMessage() {}

func (x *CallSession) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallSession.ProtoReflect.Descriptor instead.
func (*CallSession) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{0}
}

func (x *CallSession) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CallSession) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *CallSession) GetCalleeId() string {
	if x != nil {
		return x.CalleeId
	}
	return ""
}

func (x *CallSession) GetCallType() CallType {
	if x != nil {
		return x.CallType
	}
	return CallType_CALL_TYPE_AUDIO
}

func (x *CallSession) GetStatus() CallStatus {
	if x != nil {
		return x.Status
	}
	return CallStatus_CALL_STATUS_RINGING
}

func (x *CallSession) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *CallSession) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *CallSession) GetConnectedAt() int64 {
	if x != nil {
		return x.ConnectedAt
	}
	return 0
}

func (x *CallSession) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

func (x *CallSession) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CallSession) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type InitiateCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallerId      string                 `protobuf:"bytes,1,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	CalleeId      string                 `protobuf:"bytes,2,opt,name=callee_id,json=calleeId,proto3" json:"callee_id,omitempty"`
	CallType      CallType               `protobuf:"varint,3,opt,name=call_type,json=callType,proto3,enum=anychat.rtc.CallType" json:"call_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateCallRequest) Reset() {
	*x = InitiateCallRequest{}
	mi := &file_rtc_rtc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateCallRequest) ProtoMessage() {}

func (x *InitiateCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateCallRequest.ProtoReflect.Descriptor instead.
func (*InitiateCallRequest) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateCallRequest) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *InitiateCallRequest) GetCalleeId() string {
	if x != nil {
		return x.CalleeId
	}
	return ""
}

func (x *InitiateCallRequest) GetCallType() CallType {
	if x != nil {
		return x.CallType
	}
	return CallType_CALL_TYPE_AUDIO
}

type InitiateCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // RTC JWT，主叫方使用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateCallResponse) Reset() {
	*x = InitiateCallResponse{}
	mi := &file_rtc_rtc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateCallResponse) ProtoMessage() {}

func (x *InitiateCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateCallResponse.ProtoReflect.Descriptor instead.
func (*InitiateCallResponse) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{2}
}

func (x *InitiateCallResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *InitiateCallResponse) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *InitiateCallResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JoinCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 被叫方 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCallRequest) Reset() {
	*x = JoinCallRequest{}
	mi := &file_rtc_rtc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCallRequest) ProtoMessage() {}

func (x *JoinCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCallRequest.ProtoReflect.Descriptor instead.
func (*JoinCallRequest) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{3}
}

func (x *JoinCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *JoinCallRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type JoinCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // RTC JWT，被叫方使用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCallResponse) Reset() {
	*x = JoinCallResponse{}
	mi := &file_rtc_rtc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCallResponse) ProtoMessage() {}

func (x *JoinCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCallResponse.ProtoReflect.Descriptor instead.
func (*JoinCallResponse) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{4}
}

func (x *JoinCallResponse) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *JoinCallResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RejectCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectCallRequest) Reset() {
	*x = RejectCallRequest{}
	mi := &file_rtc_rtc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectCallRequest) ProtoMessage() {}

func (x *RejectCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectCallRequest.ProtoReflect.Descriptor instead.
func (*RejectCallRequest) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{5}
}

func (x *RejectCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *RejectCallRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type EndCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndCallRequest) Reset() {
	*x = EndCallRequest{}
	mi := &file_rtc_rtc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCallRequest) ProtoMessage() {}

func (x *EndCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCallRequest.ProtoReflect.Descriptor instead.
func (*EndCallRequest) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{6}
}

func (x *EndCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *EndCallRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCallSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用于鉴权（必须是参与者）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallSessionRequest) Reset() {
	*x = GetCallSessionRequest{}
	mi := &file_rtc_rtc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallSessionRequest) ProtoMessage() {}

func (x *GetCallSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallSessionRequest.ProtoReflect.Descriptor instead.
func (*GetCallSessionRequest) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{7}
}

func (x *GetCallSessionRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *GetCallSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListCallLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCallLogsRequest) Reset() {
	*x = ListCallLogsRequest{}
	mi := &file_rtc_rtc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCallLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCallLogsRequest) ProtoMessage() {}

func (x *ListCallLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCallLogsRequest.ProtoReflect.Descriptor instead.
func (*ListCallLogsRequest) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{8}
}

func (x *ListCallLogsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListCallLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCallLogsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCallLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*CallSession         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCallLogsResponse) Reset() {
	*x = ListCallLogsResponse{}
	mi := &file_rtc_rtc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCallLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCallLogsResponse) ProtoMessage() {}

func (x *ListCallLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCallLogsResponse.ProtoReflect.Descriptor instead.
func (*ListCallLogsResponse) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{9}
}

func (x *ListCallLogsResponse) GetSessions() []*CallSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListCallLogsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// MeetingRoom 会议室
type MeetingRoom struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	CreatorId       string                 `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	RoomName        string                 `protobuf:"bytes,4,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"` // RTC Room 名称
	HasPassword     bool                   `protobuf:"varint,5,opt,name=has_password,json=hasPassword,proto3" json:"has_password,omitempty"`
	MaxParticipants int32                  `protobuf:"varint,6,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	Status          MeetingStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=anychat.rtc.MeetingStatus" json:"status,omitempty"`
	StartedAt       int64                  `protobuf:"varint,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt         int64                  `protobuf:"varint,9,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MeetingRoom) Reset() {
	*x = MeetingRoom{}
	mi := &file_rtc_rtc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingRoom) ProtoMessage() {}

func (x *MeetingRoom) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingRoom.ProtoReflect.Descriptor instead.
func (*MeetingRoom) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{10}
}

func (x *MeetingRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MeetingRoom) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *MeetingRoom) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MeetingRoom) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *MeetingRoom) GetHasPassword() bool {
	if x != nil {
		return x.HasPassword
	}
	return false
}

func (x *MeetingRoom) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *MeetingRoom) GetStatus() MeetingStatus {
	if x != nil {
		return x.Status
	}
	return MeetingStatus_MEETING_STATUS_ACTIVE
}

func (x *MeetingRoom) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *MeetingRoom) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

func (x *MeetingRoom) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateMeetingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CreatorId       string                 `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Password        string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`                                       // 可选，不设则公开
	MaxParticipants int32                  `protobuf:"varint,4,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"` // 0 = 不限
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateMeetingRequest) Reset() {
	*x = CreateMeetingRequest{}
	mi := &file_rtc_rtc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetingRequest) ProtoMessage() {}

func (x *CreateMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetingRequest.ProtoReflect.Descriptor instead.
func (*CreateMeetingRequest) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{11}
}

func (x *CreateMeetingRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *CreateMeetingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMeetingRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateMeetingRequest) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

type CreateMeetingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meeting       *MeetingRoom           `protobuf:"bytes,1,opt,name=meeting,proto3" json:"meeting,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // 创建者的 RTC JWT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMeetingResponse) Reset() {
	*x = CreateMeetingResponse{}
	mi := &file_rtc_rtc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetingResponse) ProtoMessage() {}

func (x *CreateMeetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetingResponse.ProtoReflect.Descriptor instead.
func (*CreateMeetingResponse) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{12}
}

func (x *CreateMeetingResponse) GetMeeting() *MeetingRoom {
	if x != nil {
		return x.Meeting
	}
	return nil
}

func (x *CreateMeetingResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JoinMeetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"` // 若会议室有密码则必填
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinMeetingRequest) Reset() {
	*x = JoinMeetingRequest{}
	mi := &file_rtc_rtc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMeetingRequest) ProtoMessage() {}

func (x *JoinMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMeetingRequest.ProtoReflect.Descriptor instead.
func (*JoinMeetingRequest) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{13}
}

func (x *JoinMeetingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinMeetingRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinMeetingRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type JoinMeetingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meeting       *MeetingRoom           `protobuf:"bytes,1,opt,name=meeting,proto3" json:"meeting,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // RTC JWT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinMeetingResponse) Reset() {
	*x = JoinMeetingResponse{}
	mi := &file_rtc_rtc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinMeetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMeetingResponse) ProtoMessage() {}

func (x *JoinMeetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMeetingResponse.ProtoReflect.Descriptor instead.
func (*JoinMeetingResponse) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{14}
}

func (x *JoinMeetingResponse) GetMeeting() *MeetingRoom {
	if x != nil {
		return x.Meeting
	}
	return nil
}

func (x *JoinMeetingResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type EndMeetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	CreatorId     string                 `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"` // 只有创建者可结束
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndMeetingRequest) Reset() {
	*x = EndMeetingRequest{}
	mi := &file_rtc_rtc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndMeetingRequest) ProtoMessage() {}

func (x *EndMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndMeetingRequest.ProtoReflect.Descriptor instead.
func (*EndMeetingRequest) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{15}
}

func (x *EndMeetingRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *EndMeetingRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

type GetMeetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingRequest) Reset() {
	*x = GetMeetingRequest{}
	mi := &file_rtc_rtc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingRequest) ProtoMessage() {}

func (x *GetMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingRequest.ProtoReflect.Descriptor instead.
func (*GetMeetingRequest) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{16}
}

func (x *GetMeetingRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type ListMeetingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMeetingsRequest) Reset() {
	*x = ListMeetingsRequest{}
	mi := &file_rtc_rtc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMeetingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeetingsRequest) ProtoMessage() {}

func (x *ListMeetingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeetingsRequest.ProtoReflect.Descriptor instead.
func (*ListMeetingsRequest) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{17}
}

func (x *ListMeetingsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMeetingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMeetingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meetings      []*MeetingRoom         `protobuf:"bytes,1,rep,name=meetings,proto3" json:"meetings,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMeetingsResponse) Reset() {
	*x = ListMeetingsResponse{}
	mi := &file_rtc_rtc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMeetingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeetingsResponse) ProtoMessage() {}

func (x *ListMeetingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_rtc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeetingsResponse.ProtoReflect.Descriptor instead.
func (*ListMeetingsResponse) Descriptor() ([]byte, []int) {
	return file_rtc_rtc_proto_rawDescGZIP(), []int{18}
}

func (x *ListMeetingsResponse) GetMeetings() []*MeetingRoom {
	if x != nil {
		return x.Meetings
	}
	return nil
}

func (x *ListMeetingsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_rtc_rtc_proto protoreflect.FileDescriptor

const file_rtc_rtc_proto_rawDesc = "" +
	"\n" +
	"\rrtc/rtc.proto\x12\vanychat.rtc\x1a\x13common/common.proto\"\xfa\x02\n" +
	"\vCallSession\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\tcaller_id\x18\x02 \x01(\tR\bcallerId\x12\x1b\n" +
	"\tcallee_id\x18\x03 \x01(\tR\bcalleeId\x122\n" +
	"\tcall_type\x18\x04 \x01(\x0e2\x15.anychat.rtc.CallTypeR\bcallType\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.anychat.rtc.CallStatusR\x06status\x12\x1b\n" +
	"\troom_name\x18\x06 \x01(\tR\broomName\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x03R\tstartedAt\x12!\n" +
	"\fconnected_at\x18\b \x01(\x03R\vconnectedAt\x12\x19\n" +
	"\bended_at\x18\t \x01(\x03R\aendedAt\x12\x1a\n" +
	"\bduration\x18\n" +
	" \x01(\x05R\bduration\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\"\x83\x01\n" +
	"\x13InitiateCallRequest\x12\x1b\n" +
	"\tcaller_id\x18\x01 \x01(\tR\bcallerId\x12\x1b\n" +
	"\tcallee_id\x18\x02 \x01(\tR\bcalleeId\x122\n" +
	"\tcall_type\x18\x03 \x01(\x0e2\x15.anychat.rtc.CallTypeR\bcallType\"b\n" +
	"\x14InitiateCallResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"C\n" +
	"\x0fJoinCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"E\n" +
	"\x10JoinCallResponse\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"E\n" +
	"\x11RejectCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"B\n" +
	"\x0eEndCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"I\n" +
	"\x15GetCallSessionRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"_\n" +
	"\x13ListCallLogsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"b\n" +
	"\x14ListCallLogsResponse\x124\n" +
	"\bsessions\x18\x01 \x03(\v2\x18.anychat.rtc.CallSessionR\bsessions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xd3\x02\n" +
	"\vMeetingRoom\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\tR\tcreatorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\troom_name\x18\x04 \x01(\tR\broomName\x12!\n" +
	"\fhas_password\x18\x05 \x01(\bR\vhasPassword\x12)\n" +
	"\x10max_participants\x18\x06 \x01(\x05R\x0fmaxParticipants\x122\n" +
	"\x06status\x18\a \x01(\x0e2\x1a.anychat.rtc.MeetingStatusR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\x03R\tstartedAt\x12\x19\n" +
	"\bended_at\x18\t \x01(\x03R\aendedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\"\x92\x01\n" +
	"\x14CreateMeetingRequest\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\tR\tcreatorId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12)\n" +
	"\x10max_participants\x18\x04 \x01(\x05R\x0fmaxParticipants\"a\n" +
	"\x15CreateMeetingResponse\x122\n" +
	"\ameeting\x18\x01 \x01(\v2\x18.anychat.rtc.MeetingRoomR\ameeting\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"b\n" +
	"\x12JoinMeetingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"_\n" +
	"\x13JoinMeetingResponse\x122\n" +
	"\ameeting\x18\x01 \x01(\v2\x18.anychat.rtc.MeetingRoomR\ameeting\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"K\n" +
	"\x11EndMeetingRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\tR\tcreatorId\",\n" +
	"\x11GetMeetingRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"F\n" +
	"\x13ListMeetingsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"b\n" +
	"\x14ListMeetingsResponse\x124\n" +
	"\bmeetings\x18\x01 \x03(\v2\x18.anychat.rtc.MeetingRoomR\bmeetings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total*4\n" +
	"\bCallType\x12\x13\n" +
	"\x0fCALL_TYPE_AUDIO\x10\x00\x12\x13\n" +
	"\x0fCALL_TYPE_VIDEO\x10\x01*\xa4\x01\n" +
	"\n" +
	"CallStatus\x12\x17\n" +
	"\x13CALL_STATUS_RINGING\x10\x00\x12\x19\n" +
	"\x15CALL_STATUS_CONNECTED\x10\x01\x12\x15\n" +
	"\x11CALL_STATUS_ENDED\x10\x02\x12\x18\n" +
	"\x14CALL_STATUS_REJECTED\x10\x03\x12\x16\n" +
	"\x12CALL_STATUS_MISSED\x10\x04\x12\x19\n" +
	"\x15CALL_STATUS_CANCELLED\x10\x05*D\n" +
	"\rMeetingStatus\x12\x19\n" +
	"\x15MEETING_STATUS_ACTIVE\x10\x00\x12\x18\n" +
	"\x14MEETING_STATUS_ENDED\x10\x012\xdf\x06\n" +
	"\n" +
	"RTCService\x12S\n" +
	"\fInitiateCall\x12 .anychat.rtc.InitiateCallRequest\x1a!.anychat.rtc.InitiateCallResponse\x12G\n" +
	"\bJoinCall\x12\x1c.anychat.rtc.JoinCallRequest\x1a\x1d.anychat.rtc.JoinCallResponse\x12C\n" +
	"\n" +
	"RejectCall\x12\x1e.anychat.rtc.RejectCallRequest\x1a\x15.anychat.common.Empty\x12=\n" +
	"\aEndCall\x12\x1b.anychat.rtc.EndCallRequest\x1a\x15.anychat.common.Empty\x12N\n" +
	"\x0eGetCallSession\x12\".anychat.rtc.GetCallSessionRequest\x1a\x18.anychat.rtc.CallSession\x12S\n" +
	"\fListCallLogs\x12 .anychat.rtc.ListCallLogsRequest\x1a!.anychat.rtc.ListCallLogsResponse\x12V\n" +
	"\rCreateMeeting\x12!.anychat.rtc.CreateMeetingRequest\x1a\".anychat.rtc.CreateMeetingResponse\x12P\n" +
	"\vJoinMeeting\x12\x1f.anychat.rtc.JoinMeetingRequest\x1a .anychat.rtc.JoinMeetingResponse\x12C\n" +
	"\n" +
	"EndMeeting\x12\x1e.anychat.rtc.EndMeetingRequest\x1a\x15.anychat.common.Empty\x12F\n" +
	"\n" +
	"GetMeeting\x12\x1e.anychat.rtc.GetMeetingRequest\x1a\x18.anychat.rtc.MeetingRoom\x12S\n" +
	"\fListMeetings\x12 .anychat.rtc.ListMeetingsRequest\x1a!.anychat.rtc.ListMeetingsResponseB/Z-github.com/anychat/server/api/proto/rtc;rtcpbb\x06proto3"

var (
	file_rtc_rtc_proto_rawDescOnce sync.Once
	file_rtc_rtc_proto_rawDescData []byte
)

func file_rtc_rtc_proto_rawDescGZIP() []byte {
	file_rtc_rtc_proto_rawDescOnce.Do(func() {
		file_rtc_rtc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rtc_rtc_proto_rawDesc), len(file_rtc_rtc_proto_rawDesc)))
	})
	return file_rtc_rtc_proto_rawDescData
}

var file_rtc_rtc_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_rtc_rtc_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_rtc_rtc_proto_goTypes = []any{
	(CallType)(0),                 // 0: anychat.rtc.CallType
	(CallStatus)(0),               // 1: anychat.rtc.CallStatus
	(MeetingStatus)(0),            // 2: anychat.rtc.MeetingStatus
	(*CallSession)(nil),           // 3: anychat.rtc.CallSession
	(*InitiateCallRequest)(nil),   // 4: anychat.rtc.InitiateCallRequest
	(*InitiateCallResponse)(nil),  // 5: anychat.rtc.InitiateCallResponse
	(*JoinCallRequest)(nil),       // 6: anychat.rtc.JoinCallRequest
	(*JoinCallResponse)(nil),      // 7: anychat.rtc.JoinCallResponse
	(*RejectCallRequest)(nil),     // 8: anychat.rtc.RejectCallRequest
	(*EndCallRequest)(nil),        // 9: anychat.rtc.EndCallRequest
	(*GetCallSessionRequest)(nil), // 10: anychat.rtc.GetCallSessionRequest
	(*ListCallLogsRequest)(nil),   // 11: anychat.rtc.ListCallLogsRequest
	(*ListCallLogsResponse)(nil),  // 12: anychat.rtc.ListCallLogsResponse
	(*MeetingRoom)(nil),           // 13: anychat.rtc.MeetingRoom
	(*CreateMeetingRequest)(nil),  // 14: anychat.rtc.CreateMeetingRequest
	(*CreateMeetingResponse)(nil), // 15: anychat.rtc.CreateMeetingResponse
	(*JoinMeetingRequest)(nil),    // 16: anychat.rtc.JoinMeetingRequest
	(*JoinMeetingResponse)(nil),   // 17: anychat.rtc.JoinMeetingResponse
	(*EndMeetingRequest)(nil),     // 18: anychat.rtc.EndMeetingRequest
	(*GetMeetingRequest)(nil),     // 19: anychat.rtc.GetMeetingRequest
	(*ListMeetingsRequest)(nil),   // 20: anychat.rtc.ListMeetingsRequest
	(*ListMeetingsResponse)(nil),  // 21: anychat.rtc.ListMeetingsResponse
	(*common.Empty)(nil),          // 22: anychat.common.Empty
}
var file_rtc_rtc_proto_depIdxs = []int32{
	0,  // 0: anychat.rtc.CallSession.call_type:type_name -> anychat.rtc.CallType
	1,  // 1: anychat.rtc.CallSession.status:type_name -> anychat.rtc.CallStatus
	0,  // 2: anychat.rtc.InitiateCallRequest.call_type:type_name -> anychat.rtc.CallType
	3,  // 3: anychat.rtc.ListCallLogsResponse.sessions:type_name -> anychat.rtc.CallSession
	2,  // 4: anychat.rtc.MeetingRoom.status:type_name -> anychat.rtc.MeetingStatus
	13, // 5: anychat.rtc.CreateMeetingResponse.meeting:type_name -> anychat.rtc.MeetingRoom
	13, // 6: anychat.rtc.JoinMeetingResponse.meeting:type_name -> anychat.rtc.MeetingRoom
	13, // 7: anychat.rtc.ListMeetingsResponse.meetings:type_name -> anychat.rtc.MeetingRoom
	4,  // 8: anychat.rtc.RTCService.InitiateCall:input_type -> anychat.rtc.InitiateCallRequest
	6,  // 9: anychat.rtc.RTCService.JoinCall:input_type -> anychat.rtc.JoinCallRequest
	8,  // 10: anychat.rtc.RTCService.RejectCall:input_type -> anychat.rtc.RejectCallRequest
	9,  // 11: anychat.rtc.RTCService.EndCall:input_type -> anychat.rtc.EndCallRequest
	10, // 12: anychat.rtc.RTCService.GetCallSession:input_type -> anychat.rtc.GetCallSessionRequest
	11, // 13: anychat.rtc.RTCService.ListCallLogs:input_type -> anychat.rtc.ListCallLogsRequest
	14, // 14: anychat.rtc.RTCService.CreateMeeting:input_type -> anychat.rtc.CreateMeetingRequest
	16, // 15: anychat.rtc.RTCService.JoinMeeting:input_type -> anychat.rtc.JoinMeetingRequest
	18, // 16: anychat.rtc.RTCService.EndMeeting:input_type -> anychat.rtc.EndMeetingRequest
	19, // 17: anychat.rtc.RTCService.GetMeeting:input_type -> anychat.rtc.GetMeetingRequest
	20, // 18: anychat.rtc.RTCService.ListMeetings:input_type -> anychat.rtc.ListMeetingsRequest
	5,  // 19: anychat.rtc.RTCService.InitiateCall:output_type -> anychat.rtc.InitiateCallResponse
	7,  // 20: anychat.rtc.RTCService.JoinCall:output_type -> anychat.rtc.JoinCallResponse
	22, // 21: anychat.rtc.RTCService.RejectCall:output_type -> anychat.common.Empty
	22, // 22: anychat.rtc.RTCService.EndCall:output_type -> anychat.common.Empty
	3,  // 23: anychat.rtc.RTCService.GetCallSession:output_type -> anychat.rtc.CallSession
	12, // 24: anychat.rtc.RTCService.ListCallLogs:output_type -> anychat.rtc.ListCallLogsResponse
	15, // 25: anychat.rtc.RTCService.CreateMeeting:output_type -> anychat.rtc.CreateMeetingResponse
	17, // 26: anychat.rtc.RTCService.JoinMeeting:output_type -> anychat.rtc.JoinMeetingResponse
	22, // 27: anychat.rtc.RTCService.EndMeeting:output_type -> anychat.common.Empty
	13, // 28: anychat.rtc.RTCService.GetMeeting:output_type -> anychat.rtc.MeetingRoom
	21, // 29: anychat.rtc.RTCService.ListMeetings:output_type -> anychat.rtc.ListMeetingsResponse
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_rtc_rtc_proto_init() }
func file_rtc_rtc_proto_init() {
	if File_rtc_rtc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rtc_rtc_proto_rawDesc), len(file_rtc_rtc_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rtc_rtc_proto_goTypes,
		DependencyIndexes: file_rtc_rtc_proto_depIdxs,
		EnumInfos:         file_rtc_rtc_proto_enumTypes,
		MessageInfos:      file_rtc_rtc_proto_msgTypes,
	}.Build()
	File_rtc_rtc_proto = out.File
	file_rtc_rtc_proto_goTypes = nil
	file_rtc_rtc_proto_depIdxs = nil
}
