// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: rtc/rtc.proto

package rtcpb

import (
	context "context"
	common "github.com/anychat/server/api/proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RTCService_InitiateCall_FullMethodName   = "/anychat.rtc.RTCService/InitiateCall"
	RTCService_JoinCall_FullMethodName       = "/anychat.rtc.RTCService/JoinCall"
	RTCService_RejectCall_FullMethodName     = "/anychat.rtc.RTCService/RejectCall"
	RTCService_EndCall_FullMethodName        = "/anychat.rtc.RTCService/EndCall"
	RTCService_GetCallSession_FullMethodName = "/anychat.rtc.RTCService/GetCallSession"
	RTCService_ListCallLogs_FullMethodName   = "/anychat.rtc.RTCService/ListCallLogs"
	RTCService_CreateMeeting_FullMethodName  = "/anychat.rtc.RTCService/CreateMeeting"
	RTCService_JoinMeeting_FullMethodName    = "/anychat.rtc.RTCService/JoinMeeting"
	RTCService_EndMeeting_FullMethodName     = "/anychat.rtc.RTCService/EndMeeting"
	RTCService_GetMeeting_FullMethodName     = "/anychat.rtc.RTCService/GetMeeting"
	RTCService_ListMeetings_FullMethodName   = "/anychat.rtc.RTCService/ListMeetings"
)

// RTCServiceClient is the client API for RTCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RTCService 音视频 RTC 服务接口（实现无关，当前由 LiveKit 提供）
type RTCServiceClient interface {
	// ── 一对一通话 ──────────────────────────────────────────
	// InitiateCall 发起通话（返回 RTC Token 供主叫方加入 Room）
	InitiateCall(ctx context.Context, in *InitiateCallRequest, opts ...grpc.CallOption) (*InitiateCallResponse, error)
	// JoinCall 接听通话（返回 RTC Token 供被叫方加入 Room）
	JoinCall(ctx context.Context, in *JoinCallRequest, opts ...grpc.CallOption) (*JoinCallResponse, error)
	// RejectCall 拒绝通话
	RejectCall(ctx context.Context, in *RejectCallRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// EndCall 挂断通话
	EndCall(ctx context.Context, in *EndCallRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// GetCallSession 获取通话会话详情
	GetCallSession(ctx context.Context, in *GetCallSessionRequest, opts ...grpc.CallOption) (*CallSession, error)
	// ListCallLogs 获取通话记录
	ListCallLogs(ctx context.Context, in *ListCallLogsRequest, opts ...grpc.CallOption) (*ListCallLogsResponse, error)
	// ── 会议室 ────────────────────────────────────────────
	// CreateMeeting 创建会议室
	CreateMeeting(ctx context.Context, in *CreateMeetingRequest, opts ...grpc.CallOption) (*CreateMeetingResponse, error)
	// JoinMeeting 加入会议室（返回 RTC Token）
	JoinMeeting(ctx context.Context, in *JoinMeetingRequest, opts ...grpc.CallOption) (*JoinMeetingResponse, error)
	// EndMeeting 结束会议室
	EndMeeting(ctx context.Context, in *EndMeetingRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// GetMeeting 获取会议室信息
	GetMeeting(ctx context.Context, in *GetMeetingRequest, opts ...grpc.CallOption) (*MeetingRoom, error)
	// ListMeetings 列举活跃会议室
	ListMeetings(ctx context.Context, in *ListMeetingsRequest, opts ...grpc.CallOption) (*ListMeetingsResponse, error)
}

type rTCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRTCServiceClient(cc grpc.ClientConnInterface) RTCServiceClient {
	return &rTCServiceClient{cc}
}

func (c *rTCServiceClient) InitiateCall(ctx context.Context, in *InitiateCallRequest, opts ...grpc.CallOption) (*InitiateCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateCallResponse)
	err := c.cc.Invoke(ctx, RTCService_InitiateCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTCServiceClient) JoinCall(ctx context.Context, in *JoinCallRequest, opts ...grpc.CallOption) (*JoinCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinCallResponse)
	err := c.cc.Invoke(ctx, RTCService_JoinCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTCServiceClient) RejectCall(ctx context.Context, in *RejectCallRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, RTCService_RejectCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTCServiceClient) EndCall(ctx context.Context, in *EndCallRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, RTCService_EndCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTCServiceClient) GetCallSession(ctx context.Context, in *GetCallSessionRequest, opts ...grpc.CallOption) (*CallSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallSession)
	err := c.cc.Invoke(ctx, RTCService_GetCallSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTCServiceClient) ListCallLogs(ctx context.Context, in *ListCallLogsRequest, opts ...grpc.CallOption) (*ListCallLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCallLogsResponse)
	err := c.cc.Invoke(ctx, RTCService_ListCallLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTCServiceClient) CreateMeeting(ctx context.Context, in *CreateMeetingRequest, opts ...grpc.CallOption) (*CreateMeetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMeetingResponse)
	err := c.cc.Invoke(ctx, RTCService_CreateMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTCServiceClient) JoinMeeting(ctx context.Context, in *JoinMeetingRequest, opts ...grpc.CallOption) (*JoinMeetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinMeetingResponse)
	err := c.cc.Invoke(ctx, RTCService_JoinMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTCServiceClient) EndMeeting(ctx context.Context, in *EndMeetingRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, RTCService_EndMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTCServiceClient) GetMeeting(ctx context.Context, in *GetMeetingRequest, opts ...grpc.CallOption) (*MeetingRoom, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeetingRoom)
	err := c.cc.Invoke(ctx, RTCService_GetMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTCServiceClient) ListMeetings(ctx context.Context, in *ListMeetingsRequest, opts ...grpc.CallOption) (*ListMeetingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMeetingsResponse)
	err := c.cc.Invoke(ctx, RTCService_ListMeetings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RTCServiceServer is the server API for RTCService service.
// All implementations must embed UnimplementedRTCServiceServer
// for forward compatibility.
//
// RTCService 音视频 RTC 服务接口（实现无关，当前由 LiveKit 提供）
type RTCServiceServer interface {
	// ── 一对一通话 ──────────────────────────────────────────
	// InitiateCall 发起通话（返回 RTC Token 供主叫方加入 Room）
	InitiateCall(context.Context, *InitiateCallRequest) (*InitiateCallResponse, error)
	// JoinCall 接听通话（返回 RTC Token 供被叫方加入 Room）
	JoinCall(context.Context, *JoinCallRequest) (*JoinCallResponse, error)
	// RejectCall 拒绝通话
	RejectCall(context.Context, *RejectCallRequest) (*common.Empty, error)
	// EndCall 挂断通话
	EndCall(context.Context, *EndCallRequest) (*common.Empty, error)
	// GetCallSession 获取通话会话详情
	GetCallSession(context.Context, *GetCallSessionRequest) (*CallSession, error)
	// ListCallLogs 获取通话记录
	ListCallLogs(context.Context, *ListCallLogsRequest) (*ListCallLogsResponse, error)
	// ── 会议室 ────────────────────────────────────────────
	// CreateMeeting 创建会议室
	CreateMeeting(context.Context, *CreateMeetingRequest) (*CreateMeetingResponse, error)
	// JoinMeeting 加入会议室（返回 RTC Token）
	JoinMeeting(context.Context, *JoinMeetingRequest) (*JoinMeetingResponse, error)
	// EndMeeting 结束会议室
	EndMeeting(context.Context, *EndMeetingRequest) (*common.Empty, error)
	// GetMeeting 获取会议室信息
	GetMeeting(context.Context, *GetMeetingRequest) (*MeetingRoom, error)
	// ListMeetings 列举活跃会议室
	ListMeetings(context.Context, *ListMeetingsRequest) (*ListMeetingsResponse, error)
	mustEmbedUnimplementedRTCServiceServer()
}

// UnimplementedRTCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRTCServiceServer struct{}

func (UnimplementedRTCServiceServer) InitiateCall(context.Context, *InitiateCallRequest) (*InitiateCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateCall not implemented")
}
func (UnimplementedRTCServiceServer) JoinCall(context.Context, *JoinCallRequest) (*JoinCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinCall not implemented")
}
func (UnimplementedRTCServiceServer) RejectCall(context.Context, *RejectCallRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectCall not implemented")
}
func (UnimplementedRTCServiceServer) EndCall(context.Context, *EndCallRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EndCall not implemented")
}
func (UnimplementedRTCServiceServer) GetCallSession(context.Context, *GetCallSessionRequest) (*CallSession, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCallSession not implemented")
}
func (UnimplementedRTCServiceServer) ListCallLogs(context.Context, *ListCallLogsRequest) (*ListCallLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCallLogs not implemented")
}
func (UnimplementedRTCServiceServer) CreateMeeting(context.Context, *CreateMeetingRequest) (*CreateMeetingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMeeting not implemented")
}
func (UnimplementedRTCServiceServer) JoinMeeting(context.Context, *JoinMeetingRequest) (*JoinMeetingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinMeeting not implemented")
}
func (UnimplementedRTCServiceServer) EndMeeting(context.Context, *EndMeetingRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EndMeeting not implemented")
}
func (UnimplementedRTCServiceServer) GetMeeting(context.Context, *GetMeetingRequest) (*MeetingRoom, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeeting not implemented")
}
func (UnimplementedRTCServiceServer) ListMeetings(context.Context, *ListMeetingsRequest) (*ListMeetingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMeetings not implemented")
}
func (UnimplementedRTCServiceServer) mustEmbedUnimplementedRTCServiceServer() {}
func (UnimplementedRTCServiceServer) testEmbeddedByValue()                    {}

// UnsafeRTCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RTCServiceServer will
// result in compilation errors.
type UnsafeRTCServiceServer interface {
	mustEmbedUnimplementedRTCServiceServer()
}

func RegisterRTCServiceServer(s grpc.ServiceRegistrar, srv RTCServiceServer) {
	// If the following call panics, it indicates UnimplementedRTCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RTCService_ServiceDesc, srv)
}

func _RTCService_InitiateCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTCServiceServer).InitiateCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTCService_InitiateCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTCServiceServer).InitiateCall(ctx, req.(*InitiateCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTCService_JoinCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTCServiceServer).JoinCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTCService_JoinCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTCServiceServer).JoinCall(ctx, req.(*JoinCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTCService_RejectCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTCServiceServer).RejectCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTCService_RejectCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTCServiceServer).RejectCall(ctx, req.(*RejectCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTCService_EndCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTCServiceServer).EndCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTCService_EndCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTCServiceServer).EndCall(ctx, req.(*EndCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTCService_GetCallSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCallSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTCServiceServer).GetCallSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTCService_GetCallSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTCServiceServer).GetCallSession(ctx, req.(*GetCallSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTCService_ListCallLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCallLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTCServiceServer).ListCallLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTCService_ListCallLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTCServiceServer).ListCallLogs(ctx, req.(*ListCallLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTCService_CreateMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTCServiceServer).CreateMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTCService_CreateMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTCServiceServer).CreateMeeting(ctx, req.(*CreateMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTCService_JoinMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTCServiceServer).JoinMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTCService_JoinMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTCServiceServer).JoinMeeting(ctx, req.(*JoinMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTCService_EndMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTCServiceServer).EndMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTCService_EndMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTCServiceServer).EndMeeting(ctx, req.(*EndMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTCService_GetMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTCServiceServer).GetMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTCService_GetMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTCServiceServer).GetMeeting(ctx, req.(*GetMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTCService_ListMeetings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMeetingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTCServiceServer).ListMeetings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTCService_ListMeetings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTCServiceServer).ListMeetings(ctx, req.(*ListMeetingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RTCService_ServiceDesc is the grpc.ServiceDesc for RTCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RTCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anychat.rtc.RTCService",
	HandlerType: (*RTCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateCall",
			Handler:    _RTCService_InitiateCall_Handler,
		},
		{
			MethodName: "JoinCall",
			Handler:    _RTCService_JoinCall_Handler,
		},
		{
			MethodName: "RejectCall",
			Handler:    _RTCService_RejectCall_Handler,
		},
		{
			MethodName: "EndCall",
			Handler:    _RTCService_EndCall_Handler,
		},
		{
			MethodName: "GetCallSession",
			Handler:    _RTCService_GetCallSession_Handler,
		},
		{
			MethodName: "ListCallLogs",
			Handler:    _RTCService_ListCallLogs_Handler,
		},
		{
			MethodName: "CreateMeeting",
			Handler:    _RTCService_CreateMeeting_Handler,
		},
		{
			MethodName: "JoinMeeting",
			Handler:    _RTCService_JoinMeeting_Handler,
		},
		{
			MethodName: "EndMeeting",
			Handler:    _RTCService_EndMeeting_Handler,
		},
		{
			MethodName: "GetMeeting",
			Handler:    _RTCService_GetMeeting_Handler,
		},
		{
			MethodName: "ListMeetings",
			Handler:    _RTCService_ListMeetings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rtc/rtc.proto",
}
