// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: user/user.proto

package userpb

import (
	common "github.com/anychat/server/api/proto/common"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetProfileRequest 获取个人资料请求
type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// UpdateProfileRequest 更新个人资料请求
type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      *string                `protobuf:"bytes,2,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	Avatar        *string                `protobuf:"bytes,3,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	Signature     *string                `protobuf:"bytes,4,opt,name=signature,proto3,oneof" json:"signature,omitempty"`
	Gender        *int32                 `protobuf:"varint,5,opt,name=gender,proto3,oneof" json:"gender,omitempty"` // 0:未知 1:男 2:女
	Birthday      *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	Region        *string                `protobuf:"bytes,7,opt,name=region,proto3,oneof" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *UpdateProfileRequest) GetSignature() string {
	if x != nil && x.Signature != nil {
		return *x.Signature
	}
	return ""
}

func (x *UpdateProfileRequest) GetGender() int32 {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return 0
}

func (x *UpdateProfileRequest) GetBirthday() *timestamp.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *UpdateProfileRequest) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

// UserProfileResponse 用户资料响应
type UserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Gender        int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday      *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Region        string                 `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	Phone         *string                `protobuf:"bytes,8,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Email         *string                `protobuf:"bytes,9,opt,name=email,proto3,oneof" json:"email,omitempty"`
	QrcodeUrl     string                 `protobuf:"bytes,10,opt,name=qrcode_url,json=qrcodeUrl,proto3" json:"qrcode_url,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileResponse) Reset() {
	*x = UserProfileResponse{}
	mi := &file_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileResponse) ProtoMessage() {}

func (x *UserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileResponse.ProtoReflect.Descriptor instead.
func (*UserProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfileResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserProfileResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserProfileResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *UserProfileResponse) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserProfileResponse) GetBirthday() *timestamp.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *UserProfileResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *UserProfileResponse) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UserProfileResponse) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UserProfileResponse) GetQrcodeUrl() string {
	if x != nil {
		return x.QrcodeUrl
	}
	return ""
}

func (x *UserProfileResponse) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetUserInfoRequest 获取用户信息请求
type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                     // 查询者ID
	TargetUserId  string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"` // 目标用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserInfoRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

// UserInfoResponse 用户信息响应
type UserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Gender        int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	IsFriend      bool                   `protobuf:"varint,7,opt,name=is_friend,json=isFriend,proto3" json:"is_friend,omitempty"`
	IsBlocked     bool                   `protobuf:"varint,8,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResponse) Reset() {
	*x = UserInfoResponse{}
	mi := &file_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResponse) ProtoMessage() {}

func (x *UserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResponse.ProtoReflect.Descriptor instead.
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfoResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfoResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfoResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfoResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *UserInfoResponse) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfoResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *UserInfoResponse) GetIsFriend() bool {
	if x != nil {
		return x.IsFriend
	}
	return false
}

func (x *UserInfoResponse) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

// SearchUsersRequest 搜索用户请求
type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *SearchUsersRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// SearchUsersResponse 搜索用户响应
type SearchUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Users         []*UserBriefInfo       `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *SearchUsersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchUsersResponse) GetUsers() []*UserBriefInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

// UserBriefInfo 用户简要信息
type UserBriefInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBriefInfo) Reset() {
	*x = UserBriefInfo{}
	mi := &file_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBriefInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBriefInfo) ProtoMessage() {}

func (x *UserBriefInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBriefInfo.ProtoReflect.Descriptor instead.
func (*UserBriefInfo) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserBriefInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserBriefInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserBriefInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserBriefInfo) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// GetSettingsRequest 获取用户设置请求
type GetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	mi := &file_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetSettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// UpdateSettingsRequest 更新用户设置请求
type UpdateSettingsRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserId                string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotificationEnabled   *bool                  `protobuf:"varint,2,opt,name=notification_enabled,json=notificationEnabled,proto3,oneof" json:"notification_enabled,omitempty"`
	SoundEnabled          *bool                  `protobuf:"varint,3,opt,name=sound_enabled,json=soundEnabled,proto3,oneof" json:"sound_enabled,omitempty"`
	VibrationEnabled      *bool                  `protobuf:"varint,4,opt,name=vibration_enabled,json=vibrationEnabled,proto3,oneof" json:"vibration_enabled,omitempty"`
	MessagePreviewEnabled *bool                  `protobuf:"varint,5,opt,name=message_preview_enabled,json=messagePreviewEnabled,proto3,oneof" json:"message_preview_enabled,omitempty"`
	FriendVerifyRequired  *bool                  `protobuf:"varint,6,opt,name=friend_verify_required,json=friendVerifyRequired,proto3,oneof" json:"friend_verify_required,omitempty"`
	SearchByPhone         *bool                  `protobuf:"varint,7,opt,name=search_by_phone,json=searchByPhone,proto3,oneof" json:"search_by_phone,omitempty"`
	SearchById            *bool                  `protobuf:"varint,8,opt,name=search_by_id,json=searchById,proto3,oneof" json:"search_by_id,omitempty"`
	Language              *string                `protobuf:"bytes,9,opt,name=language,proto3,oneof" json:"language,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateSettingsRequest) Reset() {
	*x = UpdateSettingsRequest{}
	mi := &file_user_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsRequest) ProtoMessage() {}

func (x *UpdateSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSettingsRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateSettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateSettingsRequest) GetNotificationEnabled() bool {
	if x != nil && x.NotificationEnabled != nil {
		return *x.NotificationEnabled
	}
	return false
}

func (x *UpdateSettingsRequest) GetSoundEnabled() bool {
	if x != nil && x.SoundEnabled != nil {
		return *x.SoundEnabled
	}
	return false
}

func (x *UpdateSettingsRequest) GetVibrationEnabled() bool {
	if x != nil && x.VibrationEnabled != nil {
		return *x.VibrationEnabled
	}
	return false
}

func (x *UpdateSettingsRequest) GetMessagePreviewEnabled() bool {
	if x != nil && x.MessagePreviewEnabled != nil {
		return *x.MessagePreviewEnabled
	}
	return false
}

func (x *UpdateSettingsRequest) GetFriendVerifyRequired() bool {
	if x != nil && x.FriendVerifyRequired != nil {
		return *x.FriendVerifyRequired
	}
	return false
}

func (x *UpdateSettingsRequest) GetSearchByPhone() bool {
	if x != nil && x.SearchByPhone != nil {
		return *x.SearchByPhone
	}
	return false
}

func (x *UpdateSettingsRequest) GetSearchById() bool {
	if x != nil && x.SearchById != nil {
		return *x.SearchById
	}
	return false
}

func (x *UpdateSettingsRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

// UserSettingsResponse 用户设置响应
type UserSettingsResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserId                string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotificationEnabled   bool                   `protobuf:"varint,2,opt,name=notification_enabled,json=notificationEnabled,proto3" json:"notification_enabled,omitempty"`
	SoundEnabled          bool                   `protobuf:"varint,3,opt,name=sound_enabled,json=soundEnabled,proto3" json:"sound_enabled,omitempty"`
	VibrationEnabled      bool                   `protobuf:"varint,4,opt,name=vibration_enabled,json=vibrationEnabled,proto3" json:"vibration_enabled,omitempty"`
	MessagePreviewEnabled bool                   `protobuf:"varint,5,opt,name=message_preview_enabled,json=messagePreviewEnabled,proto3" json:"message_preview_enabled,omitempty"`
	FriendVerifyRequired  bool                   `protobuf:"varint,6,opt,name=friend_verify_required,json=friendVerifyRequired,proto3" json:"friend_verify_required,omitempty"`
	SearchByPhone         bool                   `protobuf:"varint,7,opt,name=search_by_phone,json=searchByPhone,proto3" json:"search_by_phone,omitempty"`
	SearchById            bool                   `protobuf:"varint,8,opt,name=search_by_id,json=searchById,proto3" json:"search_by_id,omitempty"`
	Language              string                 `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UserSettingsResponse) Reset() {
	*x = UserSettingsResponse{}
	mi := &file_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettingsResponse) ProtoMessage() {}

func (x *UserSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettingsResponse.ProtoReflect.Descriptor instead.
func (*UserSettingsResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserSettingsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSettingsResponse) GetNotificationEnabled() bool {
	if x != nil {
		return x.NotificationEnabled
	}
	return false
}

func (x *UserSettingsResponse) GetSoundEnabled() bool {
	if x != nil {
		return x.SoundEnabled
	}
	return false
}

func (x *UserSettingsResponse) GetVibrationEnabled() bool {
	if x != nil {
		return x.VibrationEnabled
	}
	return false
}

func (x *UserSettingsResponse) GetMessagePreviewEnabled() bool {
	if x != nil {
		return x.MessagePreviewEnabled
	}
	return false
}

func (x *UserSettingsResponse) GetFriendVerifyRequired() bool {
	if x != nil {
		return x.FriendVerifyRequired
	}
	return false
}

func (x *UserSettingsResponse) GetSearchByPhone() bool {
	if x != nil {
		return x.SearchByPhone
	}
	return false
}

func (x *UserSettingsResponse) GetSearchById() bool {
	if x != nil {
		return x.SearchById
	}
	return false
}

func (x *UserSettingsResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// RefreshQRCodeRequest 刷新二维码请求
type RefreshQRCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshQRCodeRequest) Reset() {
	*x = RefreshQRCodeRequest{}
	mi := &file_user_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshQRCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshQRCodeRequest) ProtoMessage() {}

func (x *RefreshQRCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshQRCodeRequest.ProtoReflect.Descriptor instead.
func (*RefreshQRCodeRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshQRCodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// QRCodeResponse 二维码响应
type QRCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QrcodeUrl     string                 `protobuf:"bytes,1,opt,name=qrcode_url,json=qrcodeUrl,proto3" json:"qrcode_url,omitempty"`
	ExpiresAt     *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QRCodeResponse) Reset() {
	*x = QRCodeResponse{}
	mi := &file_user_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QRCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRCodeResponse) ProtoMessage() {}

func (x *QRCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRCodeResponse.ProtoReflect.Descriptor instead.
func (*QRCodeResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{12}
}

func (x *QRCodeResponse) GetQrcodeUrl() string {
	if x != nil {
		return x.QrcodeUrl
	}
	return ""
}

func (x *QRCodeResponse) GetExpiresAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// GetUserByQRCodeRequest 通过二维码获取用户请求
type GetUserByQRCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qrcode        string                 `protobuf:"bytes,1,opt,name=qrcode,proto3" json:"qrcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByQRCodeRequest) Reset() {
	*x = GetUserByQRCodeRequest{}
	mi := &file_user_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByQRCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByQRCodeRequest) ProtoMessage() {}

func (x *GetUserByQRCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByQRCodeRequest.ProtoReflect.Descriptor instead.
func (*GetUserByQRCodeRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserByQRCodeRequest) GetQrcode() string {
	if x != nil {
		return x.Qrcode
	}
	return ""
}

// UpdatePushTokenRequest 更新推送Token请求
type UpdatePushTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PushToken     string                 `protobuf:"bytes,3,opt,name=push_token,json=pushToken,proto3" json:"push_token,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"` // iOS/Android
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePushTokenRequest) Reset() {
	*x = UpdatePushTokenRequest{}
	mi := &file_user_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePushTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePushTokenRequest) ProtoMessage() {}

func (x *UpdatePushTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePushTokenRequest.ProtoReflect.Descriptor instead.
func (*UpdatePushTokenRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{14}
}

func (x *UpdatePushTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePushTokenRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UpdatePushTokenRequest) GetPushToken() string {
	if x != nil {
		return x.PushToken
	}
	return ""
}

func (x *UpdatePushTokenRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type BindPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	VerifyCode    string                 `protobuf:"bytes,3,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindPhoneRequest) Reset() {
	*x = BindPhoneRequest{}
	mi := &file_user_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindPhoneRequest) ProtoMessage() {}

func (x *BindPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindPhoneRequest.ProtoReflect.Descriptor instead.
func (*BindPhoneRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{15}
}

func (x *BindPhoneRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BindPhoneRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *BindPhoneRequest) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type BindPhoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,2,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindPhoneResponse) Reset() {
	*x = BindPhoneResponse{}
	mi := &file_user_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindPhoneResponse) ProtoMessage() {}

func (x *BindPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindPhoneResponse.ProtoReflect.Descriptor instead.
func (*BindPhoneResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{16}
}

func (x *BindPhoneResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *BindPhoneResponse) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

type ChangePhoneRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldPhoneNumber string                 `protobuf:"bytes,2,opt,name=old_phone_number,json=oldPhoneNumber,proto3" json:"old_phone_number,omitempty"`
	NewPhoneNumber string                 `protobuf:"bytes,3,opt,name=new_phone_number,json=newPhoneNumber,proto3" json:"new_phone_number,omitempty"`
	NewVerifyCode  string                 `protobuf:"bytes,4,opt,name=new_verify_code,json=newVerifyCode,proto3" json:"new_verify_code,omitempty"`
	OldVerifyCode  *string                `protobuf:"bytes,5,opt,name=old_verify_code,json=oldVerifyCode,proto3,oneof" json:"old_verify_code,omitempty"`
	DeviceId       string                 `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChangePhoneRequest) Reset() {
	*x = ChangePhoneRequest{}
	mi := &file_user_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePhoneRequest) ProtoMessage() {}

func (x *ChangePhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePhoneRequest.ProtoReflect.Descriptor instead.
func (*ChangePhoneRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{17}
}

func (x *ChangePhoneRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangePhoneRequest) GetOldPhoneNumber() string {
	if x != nil {
		return x.OldPhoneNumber
	}
	return ""
}

func (x *ChangePhoneRequest) GetNewPhoneNumber() string {
	if x != nil {
		return x.NewPhoneNumber
	}
	return ""
}

func (x *ChangePhoneRequest) GetNewVerifyCode() string {
	if x != nil {
		return x.NewVerifyCode
	}
	return ""
}

func (x *ChangePhoneRequest) GetOldVerifyCode() string {
	if x != nil && x.OldVerifyCode != nil {
		return *x.OldVerifyCode
	}
	return ""
}

func (x *ChangePhoneRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type ChangePhoneResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OldPhoneNumber string                 `protobuf:"bytes,1,opt,name=old_phone_number,json=oldPhoneNumber,proto3" json:"old_phone_number,omitempty"`
	NewPhoneNumber string                 `protobuf:"bytes,2,opt,name=new_phone_number,json=newPhoneNumber,proto3" json:"new_phone_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChangePhoneResponse) Reset() {
	*x = ChangePhoneResponse{}
	mi := &file_user_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePhoneResponse) ProtoMessage() {}

func (x *ChangePhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePhoneResponse.ProtoReflect.Descriptor instead.
func (*ChangePhoneResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{18}
}

func (x *ChangePhoneResponse) GetOldPhoneNumber() string {
	if x != nil {
		return x.OldPhoneNumber
	}
	return ""
}

func (x *ChangePhoneResponse) GetNewPhoneNumber() string {
	if x != nil {
		return x.NewPhoneNumber
	}
	return ""
}

type BindEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	VerifyCode    string                 `protobuf:"bytes,3,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindEmailRequest) Reset() {
	*x = BindEmailRequest{}
	mi := &file_user_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindEmailRequest) ProtoMessage() {}

func (x *BindEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindEmailRequest.ProtoReflect.Descriptor instead.
func (*BindEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{19}
}

func (x *BindEmailRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BindEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BindEmailRequest) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type BindEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,2,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindEmailResponse) Reset() {
	*x = BindEmailResponse{}
	mi := &file_user_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindEmailResponse) ProtoMessage() {}

func (x *BindEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindEmailResponse.ProtoReflect.Descriptor instead.
func (*BindEmailResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{20}
}

func (x *BindEmailResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BindEmailResponse) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

type ChangeEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldEmail      string                 `protobuf:"bytes,2,opt,name=old_email,json=oldEmail,proto3" json:"old_email,omitempty"`
	NewEmail      string                 `protobuf:"bytes,3,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	NewVerifyCode string                 `protobuf:"bytes,4,opt,name=new_verify_code,json=newVerifyCode,proto3" json:"new_verify_code,omitempty"`
	OldVerifyCode *string                `protobuf:"bytes,5,opt,name=old_verify_code,json=oldVerifyCode,proto3,oneof" json:"old_verify_code,omitempty"`
	DeviceId      string                 `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEmailRequest) Reset() {
	*x = ChangeEmailRequest{}
	mi := &file_user_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEmailRequest) ProtoMessage() {}

func (x *ChangeEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEmailRequest.ProtoReflect.Descriptor instead.
func (*ChangeEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{21}
}

func (x *ChangeEmailRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangeEmailRequest) GetOldEmail() string {
	if x != nil {
		return x.OldEmail
	}
	return ""
}

func (x *ChangeEmailRequest) GetNewEmail() string {
	if x != nil {
		return x.NewEmail
	}
	return ""
}

func (x *ChangeEmailRequest) GetNewVerifyCode() string {
	if x != nil {
		return x.NewVerifyCode
	}
	return ""
}

func (x *ChangeEmailRequest) GetOldVerifyCode() string {
	if x != nil && x.OldVerifyCode != nil {
		return *x.OldVerifyCode
	}
	return ""
}

func (x *ChangeEmailRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type ChangeEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldEmail      string                 `protobuf:"bytes,1,opt,name=old_email,json=oldEmail,proto3" json:"old_email,omitempty"`
	NewEmail      string                 `protobuf:"bytes,2,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEmailResponse) Reset() {
	*x = ChangeEmailResponse{}
	mi := &file_user_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEmailResponse) ProtoMessage() {}

func (x *ChangeEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEmailResponse.ProtoReflect.Descriptor instead.
func (*ChangeEmailResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{22}
}

func (x *ChangeEmailResponse) GetOldEmail() string {
	if x != nil {
		return x.OldEmail
	}
	return ""
}

func (x *ChangeEmailResponse) GetNewEmail() string {
	if x != nil {
		return x.NewEmail
	}
	return ""
}

// InitUserDataRequest 初始化用户数据请求
type InitUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitUserDataRequest) Reset() {
	*x = InitUserDataRequest{}
	mi := &file_user_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitUserDataRequest) ProtoMessage() {}

func (x *InitUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitUserDataRequest.ProtoReflect.Descriptor instead.
func (*InitUserDataRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{23}
}

func (x *InitUserDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InitUserDataRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

var File_user_user_proto protoreflect.FileDescriptor

const file_user_user_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/user.proto\x12\fanychat.user\x1a\x13common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xd0\x02\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\bnickname\x18\x02 \x01(\tH\x00R\bnickname\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x03 \x01(\tH\x01R\x06avatar\x88\x01\x01\x12!\n" +
	"\tsignature\x18\x04 \x01(\tH\x02R\tsignature\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\x05 \x01(\x05H\x03R\x06gender\x88\x01\x01\x12;\n" +
	"\bbirthday\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\bbirthday\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\a \x01(\tH\x05R\x06region\x88\x01\x01B\v\n" +
	"\t_nicknameB\t\n" +
	"\a_avatarB\f\n" +
	"\n" +
	"_signatureB\t\n" +
	"\a_genderB\v\n" +
	"\t_birthdayB\t\n" +
	"\a_region\"\x8c\x03\n" +
	"\x13UserProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x126\n" +
	"\bbirthday\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bbirthday\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\x12\x19\n" +
	"\x05phone\x18\b \x01(\tH\x00R\x05phone\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\t \x01(\tH\x01R\x05email\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"qrcode_url\x18\n" +
	" \x01(\tR\tqrcodeUrl\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\b\n" +
	"\x06_phoneB\b\n" +
	"\x06_email\"S\n" +
	"\x12GetUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\"\xe9\x01\n" +
	"\x10UserInfoResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12\x1b\n" +
	"\tis_friend\x18\a \x01(\bR\bisFriend\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\b \x01(\bR\tisBlocked\"_\n" +
	"\x12SearchUsersRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"^\n" +
	"\x13SearchUsersResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x121\n" +
	"\x05users\x18\x02 \x03(\v2\x1b.anychat.user.UserBriefInfoR\x05users\"z\n" +
	"\rUserBriefInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\"-\n" +
	"\x12GetSettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xdb\x04\n" +
	"\x15UpdateSettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x126\n" +
	"\x14notification_enabled\x18\x02 \x01(\bH\x00R\x13notificationEnabled\x88\x01\x01\x12(\n" +
	"\rsound_enabled\x18\x03 \x01(\bH\x01R\fsoundEnabled\x88\x01\x01\x120\n" +
	"\x11vibration_enabled\x18\x04 \x01(\bH\x02R\x10vibrationEnabled\x88\x01\x01\x12;\n" +
	"\x17message_preview_enabled\x18\x05 \x01(\bH\x03R\x15messagePreviewEnabled\x88\x01\x01\x129\n" +
	"\x16friend_verify_required\x18\x06 \x01(\bH\x04R\x14friendVerifyRequired\x88\x01\x01\x12+\n" +
	"\x0fsearch_by_phone\x18\a \x01(\bH\x05R\rsearchByPhone\x88\x01\x01\x12%\n" +
	"\fsearch_by_id\x18\b \x01(\bH\x06R\n" +
	"searchById\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\t \x01(\tH\aR\blanguage\x88\x01\x01B\x17\n" +
	"\x15_notification_enabledB\x10\n" +
	"\x0e_sound_enabledB\x14\n" +
	"\x12_vibration_enabledB\x1a\n" +
	"\x18_message_preview_enabledB\x19\n" +
	"\x17_friend_verify_requiredB\x12\n" +
	"\x10_search_by_phoneB\x0f\n" +
	"\r_search_by_idB\v\n" +
	"\t_language\"\x88\x03\n" +
	"\x14UserSettingsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\x14notification_enabled\x18\x02 \x01(\bR\x13notificationEnabled\x12#\n" +
	"\rsound_enabled\x18\x03 \x01(\bR\fsoundEnabled\x12+\n" +
	"\x11vibration_enabled\x18\x04 \x01(\bR\x10vibrationEnabled\x126\n" +
	"\x17message_preview_enabled\x18\x05 \x01(\bR\x15messagePreviewEnabled\x124\n" +
	"\x16friend_verify_required\x18\x06 \x01(\bR\x14friendVerifyRequired\x12&\n" +
	"\x0fsearch_by_phone\x18\a \x01(\bR\rsearchByPhone\x12 \n" +
	"\fsearch_by_id\x18\b \x01(\bR\n" +
	"searchById\x12\x1a\n" +
	"\blanguage\x18\t \x01(\tR\blanguage\"/\n" +
	"\x14RefreshQRCodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"j\n" +
	"\x0eQRCodeResponse\x12\x1d\n" +
	"\n" +
	"qrcode_url\x18\x01 \x01(\tR\tqrcodeUrl\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"0\n" +
	"\x16GetUserByQRCodeRequest\x12\x16\n" +
	"\x06qrcode\x18\x01 \x01(\tR\x06qrcode\"\x89\x01\n" +
	"\x16UpdatePushTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"push_token\x18\x03 \x01(\tR\tpushToken\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\"o\n" +
	"\x10BindPhoneRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\x12\x1f\n" +
	"\vverify_code\x18\x03 \x01(\tR\n" +
	"verifyCode\"U\n" +
	"\x11BindPhoneResponse\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x02 \x01(\bR\tisPrimary\"\x87\x02\n" +
	"\x12ChangePhoneRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\x10old_phone_number\x18\x02 \x01(\tR\x0eoldPhoneNumber\x12(\n" +
	"\x10new_phone_number\x18\x03 \x01(\tR\x0enewPhoneNumber\x12&\n" +
	"\x0fnew_verify_code\x18\x04 \x01(\tR\rnewVerifyCode\x12+\n" +
	"\x0fold_verify_code\x18\x05 \x01(\tH\x00R\roldVerifyCode\x88\x01\x01\x12\x1b\n" +
	"\tdevice_id\x18\x06 \x01(\tR\bdeviceIdB\x12\n" +
	"\x10_old_verify_code\"i\n" +
	"\x13ChangePhoneResponse\x12(\n" +
	"\x10old_phone_number\x18\x01 \x01(\tR\x0eoldPhoneNumber\x12(\n" +
	"\x10new_phone_number\x18\x02 \x01(\tR\x0enewPhoneNumber\"b\n" +
	"\x10BindEmailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1f\n" +
	"\vverify_code\x18\x03 \x01(\tR\n" +
	"verifyCode\"H\n" +
	"\x11BindEmailResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x02 \x01(\bR\tisPrimary\"\xed\x01\n" +
	"\x12ChangeEmailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\told_email\x18\x02 \x01(\tR\boldEmail\x12\x1b\n" +
	"\tnew_email\x18\x03 \x01(\tR\bnewEmail\x12&\n" +
	"\x0fnew_verify_code\x18\x04 \x01(\tR\rnewVerifyCode\x12+\n" +
	"\x0fold_verify_code\x18\x05 \x01(\tH\x00R\roldVerifyCode\x88\x01\x01\x12\x1b\n" +
	"\tdevice_id\x18\x06 \x01(\tR\bdeviceIdB\x12\n" +
	"\x10_old_verify_code\"O\n" +
	"\x13ChangeEmailResponse\x12\x1b\n" +
	"\told_email\x18\x01 \x01(\tR\boldEmail\x12\x1b\n" +
	"\tnew_email\x18\x02 \x01(\tR\bnewEmail\"J\n" +
	"\x13InitUserDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname2\x96\t\n" +
	"\vUserService\x12P\n" +
	"\n" +
	"GetProfile\x12\x1f.anychat.user.GetProfileRequest\x1a!.anychat.user.UserProfileResponse\x12V\n" +
	"\rUpdateProfile\x12\".anychat.user.UpdateProfileRequest\x1a!.anychat.user.UserProfileResponse\x12O\n" +
	"\vGetUserInfo\x12 .anychat.user.GetUserInfoRequest\x1a\x1e.anychat.user.UserInfoResponse\x12R\n" +
	"\vSearchUsers\x12 .anychat.user.SearchUsersRequest\x1a!.anychat.user.SearchUsersResponse\x12S\n" +
	"\vGetSettings\x12 .anychat.user.GetSettingsRequest\x1a\".anychat.user.UserSettingsResponse\x12Y\n" +
	"\x0eUpdateSettings\x12#.anychat.user.UpdateSettingsRequest\x1a\".anychat.user.UserSettingsResponse\x12Q\n" +
	"\rRefreshQRCode\x12\".anychat.user.RefreshQRCodeRequest\x1a\x1c.anychat.user.QRCodeResponse\x12W\n" +
	"\x0fGetUserByQRCode\x12$.anychat.user.GetUserByQRCodeRequest\x1a\x1e.anychat.user.UserInfoResponse\x12N\n" +
	"\x0fUpdatePushToken\x12$.anychat.user.UpdatePushTokenRequest\x1a\x15.anychat.common.Empty\x12L\n" +
	"\tBindPhone\x12\x1e.anychat.user.BindPhoneRequest\x1a\x1f.anychat.user.BindPhoneResponse\x12R\n" +
	"\vChangePhone\x12 .anychat.user.ChangePhoneRequest\x1a!.anychat.user.ChangePhoneResponse\x12L\n" +
	"\tBindEmail\x12\x1e.anychat.user.BindEmailRequest\x1a\x1f.anychat.user.BindEmailResponse\x12R\n" +
	"\vChangeEmail\x12 .anychat.user.ChangeEmailRequest\x1a!.anychat.user.ChangeEmailResponse\x12H\n" +
	"\fInitUserData\x12!.anychat.user.InitUserDataRequest\x1a\x15.anychat.common.EmptyB1Z/github.com/anychat/server/api/proto/user;userpbb\x06proto3"

var (
	file_user_user_proto_rawDescOnce sync.Once
	file_user_user_proto_rawDescData []byte
)

func file_user_user_proto_rawDescGZIP() []byte {
	file_user_user_proto_rawDescOnce.Do(func() {
		file_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)))
	})
	return file_user_user_proto_rawDescData
}

var file_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_user_user_proto_goTypes = []any{
	(*GetProfileRequest)(nil),      // 0: anychat.user.GetProfileRequest
	(*UpdateProfileRequest)(nil),   // 1: anychat.user.UpdateProfileRequest
	(*UserProfileResponse)(nil),    // 2: anychat.user.UserProfileResponse
	(*GetUserInfoRequest)(nil),     // 3: anychat.user.GetUserInfoRequest
	(*UserInfoResponse)(nil),       // 4: anychat.user.UserInfoResponse
	(*SearchUsersRequest)(nil),     // 5: anychat.user.SearchUsersRequest
	(*SearchUsersResponse)(nil),    // 6: anychat.user.SearchUsersResponse
	(*UserBriefInfo)(nil),          // 7: anychat.user.UserBriefInfo
	(*GetSettingsRequest)(nil),     // 8: anychat.user.GetSettingsRequest
	(*UpdateSettingsRequest)(nil),  // 9: anychat.user.UpdateSettingsRequest
	(*UserSettingsResponse)(nil),   // 10: anychat.user.UserSettingsResponse
	(*RefreshQRCodeRequest)(nil),   // 11: anychat.user.RefreshQRCodeRequest
	(*QRCodeResponse)(nil),         // 12: anychat.user.QRCodeResponse
	(*GetUserByQRCodeRequest)(nil), // 13: anychat.user.GetUserByQRCodeRequest
	(*UpdatePushTokenRequest)(nil), // 14: anychat.user.UpdatePushTokenRequest
	(*BindPhoneRequest)(nil),       // 15: anychat.user.BindPhoneRequest
	(*BindPhoneResponse)(nil),      // 16: anychat.user.BindPhoneResponse
	(*ChangePhoneRequest)(nil),     // 17: anychat.user.ChangePhoneRequest
	(*ChangePhoneResponse)(nil),    // 18: anychat.user.ChangePhoneResponse
	(*BindEmailRequest)(nil),       // 19: anychat.user.BindEmailRequest
	(*BindEmailResponse)(nil),      // 20: anychat.user.BindEmailResponse
	(*ChangeEmailRequest)(nil),     // 21: anychat.user.ChangeEmailRequest
	(*ChangeEmailResponse)(nil),    // 22: anychat.user.ChangeEmailResponse
	(*InitUserDataRequest)(nil),    // 23: anychat.user.InitUserDataRequest
	(*timestamp.Timestamp)(nil),    // 24: google.protobuf.Timestamp
	(*common.Empty)(nil),           // 25: anychat.common.Empty
}
var file_user_user_proto_depIdxs = []int32{
	24, // 0: anychat.user.UpdateProfileRequest.birthday:type_name -> google.protobuf.Timestamp
	24, // 1: anychat.user.UserProfileResponse.birthday:type_name -> google.protobuf.Timestamp
	24, // 2: anychat.user.UserProfileResponse.created_at:type_name -> google.protobuf.Timestamp
	7,  // 3: anychat.user.SearchUsersResponse.users:type_name -> anychat.user.UserBriefInfo
	24, // 4: anychat.user.QRCodeResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 5: anychat.user.UserService.GetProfile:input_type -> anychat.user.GetProfileRequest
	1,  // 6: anychat.user.UserService.UpdateProfile:input_type -> anychat.user.UpdateProfileRequest
	3,  // 7: anychat.user.UserService.GetUserInfo:input_type -> anychat.user.GetUserInfoRequest
	5,  // 8: anychat.user.UserService.SearchUsers:input_type -> anychat.user.SearchUsersRequest
	8,  // 9: anychat.user.UserService.GetSettings:input_type -> anychat.user.GetSettingsRequest
	9,  // 10: anychat.user.UserService.UpdateSettings:input_type -> anychat.user.UpdateSettingsRequest
	11, // 11: anychat.user.UserService.RefreshQRCode:input_type -> anychat.user.RefreshQRCodeRequest
	13, // 12: anychat.user.UserService.GetUserByQRCode:input_type -> anychat.user.GetUserByQRCodeRequest
	14, // 13: anychat.user.UserService.UpdatePushToken:input_type -> anychat.user.UpdatePushTokenRequest
	15, // 14: anychat.user.UserService.BindPhone:input_type -> anychat.user.BindPhoneRequest
	17, // 15: anychat.user.UserService.ChangePhone:input_type -> anychat.user.ChangePhoneRequest
	19, // 16: anychat.user.UserService.BindEmail:input_type -> anychat.user.BindEmailRequest
	21, // 17: anychat.user.UserService.ChangeEmail:input_type -> anychat.user.ChangeEmailRequest
	23, // 18: anychat.user.UserService.InitUserData:input_type -> anychat.user.InitUserDataRequest
	2,  // 19: anychat.user.UserService.GetProfile:output_type -> anychat.user.UserProfileResponse
	2,  // 20: anychat.user.UserService.UpdateProfile:output_type -> anychat.user.UserProfileResponse
	4,  // 21: anychat.user.UserService.GetUserInfo:output_type -> anychat.user.UserInfoResponse
	6,  // 22: anychat.user.UserService.SearchUsers:output_type -> anychat.user.SearchUsersResponse
	10, // 23: anychat.user.UserService.GetSettings:output_type -> anychat.user.UserSettingsResponse
	10, // 24: anychat.user.UserService.UpdateSettings:output_type -> anychat.user.UserSettingsResponse
	12, // 25: anychat.user.UserService.RefreshQRCode:output_type -> anychat.user.QRCodeResponse
	4,  // 26: anychat.user.UserService.GetUserByQRCode:output_type -> anychat.user.UserInfoResponse
	25, // 27: anychat.user.UserService.UpdatePushToken:output_type -> anychat.common.Empty
	16, // 28: anychat.user.UserService.BindPhone:output_type -> anychat.user.BindPhoneResponse
	18, // 29: anychat.user.UserService.ChangePhone:output_type -> anychat.user.ChangePhoneResponse
	20, // 30: anychat.user.UserService.BindEmail:output_type -> anychat.user.BindEmailResponse
	22, // 31: anychat.user.UserService.ChangeEmail:output_type -> anychat.user.ChangeEmailResponse
	25, // 32: anychat.user.UserService.InitUserData:output_type -> anychat.common.Empty
	19, // [19:33] is the sub-list for method output_type
	5,  // [5:19] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_user_user_proto_init() }
func file_user_user_proto_init() {
	if File_user_user_proto != nil {
		return
	}
	file_user_user_proto_msgTypes[1].OneofWrappers = []any{}
	file_user_user_proto_msgTypes[2].OneofWrappers = []any{}
	file_user_user_proto_msgTypes[9].OneofWrappers = []any{}
	file_user_user_proto_msgTypes[17].OneofWrappers = []any{}
	file_user_user_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_proto_goTypes,
		DependencyIndexes: file_user_user_proto_depIdxs,
		MessageInfos:      file_user_user_proto_msgTypes,
	}.Build()
	File_user_user_proto = out.File
	file_user_user_proto_goTypes = nil
	file_user_user_proto_depIdxs = nil
}
